#!/bin/sh
# - events
# - freq
# - delay
# - duration

perf=/lkp/benchmarks/perf-report-srcline/perf
[ -x "$perf" ] || {
    command -v perf > /dev/null || exit
    perf="perf"
}

default_events()
{
	for event in cycles:pp cycles:p; do
		$perf record -q --freq=800 -e $event -- sleep 0.01 >/dev/null 2>&1 && {
			echo $event
			return
		}
	done
	echo cycles
}

: ${events:=$(default_events)}
: ${duration:=10}
: ${delay:=100}

[ -n "$freq" ] &&
opt_freq="--freq=$freq"
opt_events="-e $(echo "$events" | sed 's/ / -e /g')"

# perf may consume lots of fd
ulimit -n 102400

. $LKP_SRC/lib/wait.sh
setup_wait

$perf record -q -ag --realtime=1 -m 256 $opt_freq $opt_events \
	-o $TMP/perf-report-srcline.data -D $((delay * 1000)) -- \
	timeout $((delay + duration)) \
	$WAIT_POST_TEST_CMD
