#!/bin/sh
# - events
# - period
# - freq
# - delay
# - duration

perf=/lkp/benchmarks/perf-profile/perf

default_events()
{
	for event in cycles:pp cycles:p; do
		$perf record -q --freq=800 -e $event -- sleep 0.01 >/dev/null 2>&1 && {
			echo $event
			return
		}
	done
	echo cycles
}

: ${events:=$(default_events)}
: ${duration:=100}
: ${period:=1000003}

if [ -z "$delay" ]; then
	if [ -n "$runtime" ]; then
		delay=$((runtime / 2))
	else
		delay=100
	fi
fi

[ -n "$freq" ] &&
opt_freq="--freq=$freq"

[ -n "$period" ] &&
opt_period="--count=$period"

opt_events="-e $(echo "$events" | sed 's/ / -e /g')"

# perf may consume lots of fd
ulimit -n 102400

. $LKP_SRC/lib/wait.sh
setup_wait

$perf record -q -ag --realtime=1 -m 256 $opt_freq $opt_period $opt_events \
	-o $TMP/perf.data -D $((delay * 1000)) -- \
	$WAIT_POST_TEST_CMD --timeout $((duration))
