AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/constant-shared.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 30
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/NumericPredicate:
  Exclude:
    - 'lib/job2sh.rb'
    - 'lib/matrix.rb'
    - 'lib/stats.rb'
