AllCops:
  TargetRubyVersion: 2.5
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 30
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/GlobalVars:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'lib/job2sh.rb'
    - 'lib/matrix.rb'
    - 'lib/stats.rb'

Security/Eval:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
