#!/bin/sh

# Archlinux package installation

# Yet Another Yogurt - An AUR Helper Written in Go
# Yay is based on the design of yaourt, apacman and pacaur
# See: https://github.com/Jguer/yay

# Yay not support root to build package
# Use regular user to do this
. $LKP_SRC/distro/${DISTRO}
add_aur_helper

regular_user=$(grep 1090 /etc/passwd | awk -F':' '{ print $1 }')

sudo -u $regular_user yay -S --needed --noconfirm $*
