#!/bin/bash

if ! rpm -q epel-release >/dev/null; then
	[ ${DISTRO^^} == "OPENEULER" ] || yum install -yq epel-release
	if [ ${DISTRO^^} == "OPENEULER" ]; then
		yum makecache timer >/dev/null
	else
		yum makecache fast >/dev/null
	fi
fi

yum install -yq $*
