#!/bin/bash

if ! rpm -q epel-release >/dev/null; then
	[ ${DISTRO^^} == "OPENEULER" ] || yum install -y epel-release
	if [ ${DISTRO^^} == "OPENEULER" ]; then
		yum makecache timer
	else
		yum makecache fast
	fi
fi

yum install -y $*
