#!/bin/sh

# Debian package installation
export DEBIAN_FRONTEND=noninteractive
dpkg --add-architecture i386 && apt-get update
apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" \
     -y install $*
