#!/bin/sh
# - runtime
# - concurrency

. $LKP_SRC/lib/reproduce-log.sh

[ -n "$direct_server_ips" ] && server=$direct_server_ips
[ -z "$server" ] && server=127.0.0.1
server=${server%% *}

[ -n "$runtime" ] || runtime=300
[ -n "$concurrency" ] || concurrency=1000

log_cmd ab -k -q -t $runtime -n 1000000000000 -c $concurrency $server/
