#!/bin/sh
# - test

. $LKP_SRC/lib/upload.sh

## Autotest is a framework for fully automated testing. It is designed
## primarily to test the Linux kernel, though it is useful for many
## other functions such as qualifying new hardware.

cd $BENCHMARK_ROOT/autotest || exit

(
	cd /usr/bin
	[ -x "automake"	] || ln -s automake-* automake
	[ -x "aclocal"	] || ln -s aclocal-* aclocal
)

log_cmd client/autotest-local run $test 2>&1 || exit

exit_value=$?

upload_files $BENCHMARK_ROOT/autotest/client/results/default

exit $exit_value
