#!/bin/sh
# - test

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/debug.sh

## Autotest is a framework for fully automated testing. It is designed
## primarily to test the Linux kernel, though it is useful for many
## other functions such as qualifying new hardware.

cd $BENCHMARK_ROOT/autotest || exit

(
	cd /usr/bin
	[ -x "automake"	] || ln -s automake-* automake
	[ -x "aclocal"	] || ln -s aclocal-* aclocal
)

[ "$test" = "cgroup_tests" ] && {
	cgconfig_script="/usr/share/doc/cgroup-tools/examples/cgconfig"
	[ -f "$cgconfig_script" ] && {
		[ -x "$cgconfig_script" ] || chmod +x $cgconfig_script
		log_cmd cp $cgconfig_script /etc/init.d/

		# FIX: [Errno 2] No such file or directory: '/cgroup/memory/test2/tasks
		sed -i "/cgclear/s/^/#/" /etc/init.d/cgconfig
		sed -i '/#    cgclear/a\    cgclear\n    rm -f "$lockfile" && log_success_msg && return 0' /etc/init.d/cgconfig
	}

	log_cmd cp $LKP_SRC/pack/autotest-addon/cgconfig.conf /etc

	log_cmd update-rc.d cgconfig defaults || die "failed toadd service cgconfig"
	log_cmd service cgconfig restart || die "failed to restart cgconfig"
}

iface=$(ifconfig -s | awk '{print $1}' | grep ^eth | head -1)
[ -n "$iface" -a "$iface" != "eth0" ] && sed -i "s/eth='eth0'/eth='$iface'/g" client/tests/pktgen/control

log_cmd python2.7 client/autotest-local run $test 2>&1 || exit

exit_value=$?

upload_files -t results $BENCHMARK_ROOT/autotest/client/results/default

exit $exit_value
