#!/bin/bash
# - dpdk_branch
# - dpdk_commit
# - dpdk_config
# - dpdk_compiler
# - branch
# - commit

## DPDK is a set of libraries and drivers for fast packet processing.
## It was designed to run on any processors knowing Intel x86 has
## been the first CPU to be supported. Ports for other CPUs like
## IBM Power 8 are under progress. It runs mostly in Linux userland.
## A FreeBSD port is now available for a subset of DPDK features.

shopt -s nullglob

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/build.sh
. $LKP_SRC/lib/mount.sh
. $LKP_SRC/lib/git.sh

merge_configs()
{
	local config_file=$1
	local dot_config=$DPDK_OBJ/.config
	local lines="$(awk -F= '!x[$1]++' $config_file $dot_config)"
	echo "$lines" > $dot_config
}

DPDK_SRC=/build/dpdk/src
DPDK_OBJ=/build/dpdk/obj
export RTE_KERNELDIR=/build/linux/src

ARCH=${dpdk_config%%-*}
dpdk_compiler_name=${dpdk_compiler%%-*}

[[ $dpdk_branch ]] || dpdk_branch='dpdk/master'
dpdk_remote=${dpdk_branch%%/*}

[[ $branch ]] || branch='linus/master'
remote=${branch%%/*}

check_mount dpdk-src $DPDK_SRC -t tmpfs
check_mount dpdk-obj $DPDK_OBJ -t tmpfs
check_mount kernel-src $RTE_KERNELDIR -t tmpfs

git_clone_update git://gitmirror/$remote $RTE_KERNELDIR || die "failed clone kernel tree $remote"
cd $RTE_KERNELDIR
git checkout $commit || die "failed to checkout kernel commit $_commit"
make allmodconfig || die "make allmodconfig failed"
make prepare || die "make prepare failed"
make scripts/ || die "make scripts/ failed"

git_clone_update git://gitmirror/$dpdk_remote $DPDK_SRC || die "failed clone dpdk tree $dpdk_remote"
cd $DPDK_SRC
git checkout $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"

config_file=$LKP_SRC/etc/dpdk-configs/$dpdk_config
[ -f $config_file ] ||
config_file=$DPDK_SRC/config/defconfig_$dpdk_config
[ -f $config_file ] || die "invalid config file $config_file"

make O=$DPDK_OBJ T=$ARCH-native-linuxapp-$dpdk_compiler_name config || die "failed to make config"

[[ $config_file =~ "$DPDK_SRC/config" ]] ||
merge_configs $config_file

grep -r -l 'Werror' $DPDK_SRC | xargs sed -i 's/ -Werror//'

make O=$DPDK_OBJ DESTDIR=$RESULT_ROOT

git reset --hard

build_complete
