#!/bin/bash
# - dpdk_commit
# - dpdk_config
# - dpdk_compiler
# dpdk_branch
# branch
# commit

## DPDK is a set of libraries and drivers for fast packet processing.
## It was designed to run on any processors knowing Intel x86 has
## been the first CPU to be supported. Ports for other CPUs like
## IBM Power 8 are under progress. It runs mostly in Linux userland.
## A FreeBSD port is now available for a subset of DPDK features.

shopt -s nullglob

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/build.sh
. $LKP_SRC/lib/mount.sh
. $LKP_SRC/lib/git.sh

export CC=$dpdk_compiler
$CC -v 2>&1 || {
	echo "can not find executable $CC" >&2
	exit 1
}

merge_configs()
{
	local config_file=$1
	local dot_config=$DPDK_OBJ/.config
	local lines="$(awk -F= '!x[$1]++' $config_file $dot_config)"
	echo "$lines" > $dot_config
}

DPDK_REPO_ROOT=/build/dpdk/src
DPDK_OBJ=/build/dpdk/obj
LINUX_KERNEL_ROOT=/build/linux/src
export RTE_KERNELDIR="$LINUX_KERNEL_ROOT"

ARCH=${dpdk_config%%-*}
dpdk_compiler_name=${dpdk_compiler%%-*}

[[ $dpdk_branch ]] || dpdk_branch='dpdk/master'
dpdk_remote=${dpdk_branch%%/*}

[[ $branch ]] || branch='linus/master'
remote=${branch%%/*}

check_mount dpdk-src $DPDK_REPO_ROOT -t tmpfs
check_mount dpdk-obj $DPDK_OBJ -t tmpfs
check_mount kernel-src $LINUX_KERNEL_ROOT -t tmpfs

git_clone_update git://gitmirror/$remote $LINUX_KERNEL_ROOT || die "failed to clone kernel tree $remote"

cd $LINUX_KERNEL_ROOT
git checkout -q $commit || die "failed to checkout kernel commit $_commit"
make_config allmodconfig || die "make allmodconfig failed"
make prepare || die "make prepare failed"
make scripts/ || die "make scripts/ failed"

rm -fr "$DPDK_REPO_ROOT" 2>/dev/null
git_clone_update git://gitmirror/$dpdk_remote $DPDK_REPO_ROOT || die "failed clone dpdk tree $dpdk_remote"

cd $DPDK_REPO_ROOT
cmd git checkout -q $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"

config_file=$LKP_SRC/etc/dpdk-configs/$dpdk_config
[ -f $config_file ] || config_file=$DPDK_REPO_ROOT/config/defconfig_$dpdk_config
[ -f $config_file ] || die "invalid config file $config_file"

make O=$DPDK_OBJ T=$ARCH-native-linuxapp-$dpdk_compiler_name config || die "failed to make config"

[[ $config_file =~ "$DPDK_REPO_ROOT/config" ]] || merge_configs $config_file

grep -r -l 'Werror' $DPDK_REPO_ROOT | xargs sed -i 's/ -Werror//'

cp $DPDK_OBJ/.config $RESULT_ROOT/dpdk_config

# To fix the following error info:
# make[3]: *** [test] Error 1
# /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS): In function `_ZGVbN2v___log_finite':
# (.text+0x0): multiple definition of `_ZGVbN2v___log_finite'
# /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS):(.text+0x0): first defined here
# collect2: error: ld returned 1 exit status
# make[1]: *** [app] Error 2
# make[2]: *** [test-acl] Error 2
#
# when gcc on ld stage, it will find libmvec_nonshared.a file, so can not remove it, just link to another more popular .so library.
# and actually dpdk fully do not depend on libmvec_nonshared.a library.
ln -sf /usr/lib/x86_64-linux-gnu/libmvec.so  /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a

make O=$DPDK_OBJ DESTDIR=$RESULT_ROOT
make_exit_status=$?

build_complete $make_exit_status

git reset --hard

exit $make_exit_status
