#!/bin/bash
# - runtime
# - segments
# - nr_threads

[ -n "$segments"	] || segments=1024
[ -n "$nr_threads"	] || nr_threads=16
[ -n "$runtime"		] || runtime=600

segments=${segments%s}

cd $BENCHMARK_ROOT/bust_shm_exit || exit

cmd timeout $runtime ./bust_shm_exit $segments $nr_threads
