#!/bin/sh
# - runtime
# - segments
# - nr_threads

## Create a bunch of shared memory segments, then a bunch of
## threads that continually clone and exit.

[ -n "$segments"	] || segments=1024
[ -n "$nr_threads"	] || nr_threads=16
[ -n "$runtime"		] || runtime=600

segments=${segments%s}

cd $BENCHMARK_ROOT/bust_shm_exit || exit

log_cmd timeout $runtime ./bust_shm_exit $segments $nr_threads
