#!/bin/bash
# - benchmark
# - os_mount
# - os
# - os_arch
# - os_version

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/misc-base.sh

[ -n "$benchmark" ]	|| die "benchmark is empty"
[ -n "$os_mount" ]	|| die "os_mount is empty"
[ -n "$os" ]		|| die "os is empty"
[ -n "$os_arch" ]	|| die "os_arch is empty"
[ -n "$os_version" ]	|| die "os_version is empty"

DEPS_MNT=/initrd/deps	&& mkdir -p "$DEPS_MNT"
DISTRO=${os}

[[ "$os_mount" = "cifs" ]] && os_mount="nfs"
pack_to=${DEPS_MNT}/${os_mount}/${os}/${os_arch}/${os_version}/${benchmark}

pack_arch=$os_arch
[[ "$benchmark" = "${benchmark##*.}" ]] ||
{
        pack_arch="${benchmark##*.}"
}

. $LKP_SRC/distro/$DISTRO

umask 002

[[ -d "$pack_to" ]] || {
	mkdir -p "$pack_to"
	chown .lkp "$pack_to"
}

check_shared_package "$benchmark" && {
	ln -sf $BM_NAME.cgz $pack_to/$benchmark.cgz
	echo "create symlink for shared package: $benchmark -> $BM_NAME"

	exit 0
}

share_debian_package

distro_install_depends cci-depends

fixup_distro_mirror

update

fixup_preinstall

[[ "$benchmark" = "all" ]] && benchmark="$(ls $LKP_SRC/distro/depends | grep -v -e '-dev' -e '-allowlist')"

fixup_arch_install $pack_arch

pack_benchmark_deps

upload_to_target_dir ${pack_to}
