#!/bin/sh
# - priority
# - clock
# - interval
# - histogram
# - loops

export PATH=$BENCHMARK_ROOT/cyclictest/bin:$PATH

run_test()
{
	log_cmd cyclictest -p $priority -m -c $clock -i $interval -n -h $histogram -q -l $loops 2>&1
}

run_test
