#!/bin/sh
# - nr_threads

## DBENCH is a tool to generate I/O workloads to either a filesystem
## or to a networked CIFS or NFS server. It generates load patterns
## similar to those of the commercial Netbench benchmark, but without
## requiring a lab of Windows load generators to run.
##
## Homepage: https://dbench.samba.org/

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/debug.sh

run_dbench()
{
	client_file=/usr/local/share/client.txt
	[ -f "$client_file" ] || client_file=/usr/share/dbench/client.txt
	[ -f "$client_file" ] || die "can not find client.txt"
	log_cmd dbench $nr_threads -c $client_file
}

run_dbench
