#!/bin/sh
# - nr_threads

## DBENCH is a tool to generate I/O workloads to either a filesystem
## or to a networked CIFS or NFS server. It generates load patterns
## similar to those of the commercial Netbench benchmark, but without
## requiring a lab of Windows load generators to run.
##
## Homepage: https://dbench.samba.org/

. $LKP_SRC/lib/env.sh

run_dbench()
{
	client_dir=/usr/share/dbench
	is_clearlinux && client_dir=/usr/local/share
	log_cmd dbench $nr_threads -c $client_dir/client.txt
}

run_dbench
