#!/bin/sh -e
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

# redirect remote-repository address to "/srv/git/gitee.com"
cat >> /etc/gitconfig <<EOF
[url "git://$GIT_SERVER/gitee.com"]
	insteadOf=https://gitee.com
EOF

export initrd_http_host=$INITRD_HTTP_HOST
export initrd_http_port=$INITRD_HTTP_PORT
export gitcache_host=$GITCACHE_HOST
export gitcache_port=$GITCACHE_PORT

cd /c || exit
git clone https://gitee.com/wu_fengguang/compass-ci.git

# Need mount tmpfs to fix compass-ci/container/os-nfs/start error
# "exportfs: /exports/result does not support NFS export"
mount -t tmpfs none /srv

# test the script for one-click deployment
cd /c/compass-ci/sparrow || exit
./install-tiny
