#!/bin/bash
# - nr_threads
# - period
# - rwmode
# - iomode
# - size
# - filenum

[ -n "$period"	] || period=600
[ -n "$rwmode"	] || rwmode=rndrw
[ -n "$iomode"	] || iomode=sync
[ -n "$size"	] || size=$((128<<30))
[ -n "$filenum"	] || filenum=128

filenum=${filenum%f}

args=(
	--max-requests=0
	--num-threads=$nr_threads
	--max-time=$period
	--file-test-mode=$rwmode
	--file-total-size=$size
	--file-io-mode=$iomode
	--file-num=$filenum
)

prepare()
{
	cmd sysbench --test=fileio "${args[@]}" prepare
}

prepare_fallocate()
{
	# in seqwr mode, fileio will remove all exist files, hence
	# it's worthless to create them here.
	[ "$rwmode" = "seqwr" ] && return

	local filesize=$((size / filenum))
	for ((i = 0; i < filenum; i++))
	do
		cmd fallocate -l $filesize test_file.$i
	done
}

run()
{
	# permit more files open in system
	ulimit -n $(($filenum + 2048))
	cmd sysbench --test=fileio "${args[@]}" run
}

note cd "$mount_points"
cd "$mount_points" || exit

if [ "${rwmode#*wr}" != "$rwmode" ]; then
	prepare_fallocate
else
	prepare
fi
run
