#!/bin/sh
# - nr_task
# - samples
# - freq

## The FTQ benchmarks measure hardware and softwareinterference
## or 'noise' on a node from the applications perspective.

. $LKP_SRC/lib/upload.sh

cd $BENCHMARK_ROOT/ftq || exit

[ 0"$nr_task" -gt 1  ] && opt_task="-t $nr_task"

[ -n "$samples" ] || samples=10000

[ -n "$freq" ] && opt_freq="-f $freq"

samples=${samples%%ss}

log_cmd ./ftq $opt_freq -n $samples $opt_task || exit

exit_value=$?

upload_files -t results $BENCHMARK_ROOT/ftq/*.dat

exit $exit_value
