#!/bin/bash
# - samples

BM_NAME=$(basename $0)

cd $BENCHMARK_ROOT/$BM_NAME || exit

(( nr_threads > 1 )) && opt_threads="-t $nr_threads"

[[ $samples ]] || samples=10000

samples=${samples%%ss}

[[ $iterations ]] || iterations=20

if [[ $BM_NAME == "ftq" ]]; then
	opt_iterations="-i $iterations"
elif [[ $BM_NAME == "fwq" ]]; then
	opt_iterations="-w $iterations"
fi

cmd ./t_$BM_NAME -n $samples $opt_iterations $opt_threads

chmod g+w	$BENCHMARK_ROOT/$BM_NAME/*.dat
chown lkp.lkp	$BENCHMARK_ROOT/$BM_NAME/*.dat
cp -a		$BENCHMARK_ROOT/$BM_NAME/*.dat $RESULT_ROOT/
