#!/bin/bash

cd /sys/kernel/debug/tracing || exit

: ${runtime:=300}

do_test()
{
	for tracer in $(<available_tracers)
	do
		note "echo $tracer > current_tracer"
		      echo $tracer > current_tracer

		note "echo 1 > tracing_on"
		      echo 1 > tracing_on

		note "echo 0 > tracing_on"
		      echo 0 > tracing_on
	done
}

source $LKP_SRC/lib/runtime_loop.sh
