#!/bin/sh
# - nr_task
# - samples
# - iterations

## The FTQ and FWQ benchmarks measure hardware and softwareinterference
## or 'noise' on a node from the applications perspective.

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/reproduce-log.sh

cd $BENCHMARK_ROOT/fwq || die "no $BENCHMARK_ROOT/fwq"

[ "$nr_task" -gt 1  ] && opt_task="-t $nr_task"

[ -n "$samples" ] || samples=10000

samples=${samples%%ss}

[ -n "$iterations" ] || iterations=20

opt_iterations="-w $iterations"

log_cmd ./t_fwq -n $samples $opt_iterations $opt_task

upload_files -t results $BENCHMARK_ROOT/fwq/*.dat
