#!/bin/sh
# - nr_task
# - samples
# - iterations

## The FTQ and FWQ benchmarks measure hardware and softwareinterference
## or 'noise' on a node from the applications perspective.

. $LKP_SRC/lib/upload.sh

cd $BENCHMARK_ROOT/fwq || exit

[ "$nr_task" -gt 1  ] && opt_task="-t $nr_task"

[ -n "$samples" ] || samples=10000

samples=${samples%%ss}

[ -n "$iterations" ] || iterations=20

opt_iterations="-w $iterations"

log_cmd ./t_fwq -n $samples $opt_iterations $opt_task || exit

exit_value=$?

upload_files $BENCHMARK_ROOT/fwq/*.dat

exit $exit_value
