#!/bin/sh
# - test
# - width
# - height

[ -n "$width" ] || width=1366
[ -n "$height" ] || height=768

width=${width%w}
height=${height%h}

cd /auto/benchmarks/glbenchmark2.7.0

# export DISPLAY=:0
export vblank_mode=0

cmd ./build_x86_64/binaries/GLBenchmark -w $width -h $height -t $test
