#!/bin/sh
# - test
# - width
# - height

## GFXBench is a free, cross-platform and cross-API 3D graphics benchmark
## that measures graphics performance,long-term performance stability,
## render quality and power consumption with a single, easy-to-use application.

[ -n "$width" ] || width=1366
[ -n "$height" ] || height=768

width=${width%w}
height=${height%h}

cd /auto/benchmarks/glbenchmark2.7.0

# export DISPLAY=:0
export vblank_mode=0

log_cmd ./build_x86_64/binaries/GLBenchmark -w $width -h $height -t $test
