#!/bin/sh
# - group

## Automated hostapd/wpa_supplicant testing with mac80211_hwsim.
## See: https://github.com/jmalinen/hostap/tree/master/tests/hwsim

. $LKP_SRC/lib/debug.sh
cd $BENCHMARK_ROOT/hwsim/tests/hwsim || exit

group_file=$LKP_SRC/pack/hwsim-addon/groups/$group
[ -f "$group_file" ] || die "can not find group_file: $LKP_SRC/pack/hwsim-addon/groups/$group"

nm_conf="/etc/NetworkManager/NetworkManager.conf"
[ -f "$nm_conf" ] && cat >> $nm_conf <<EOF
[keyfile]
unmanaged-devices=mac:02:00:00:00:00:00;mac:02:00:00:00:01:00;mac:02:00:00:00:02:00;mac:02:00:00:00:03:00;mac:02:00:00:00:04:00
EOF

[ $USER ] || export USER=root

./start.sh || die "fail to setup test environment"

# here sleep is to fix below error info:
# Failed to connect to wpa_supplicant global interface: /tmp/wpas-wlan1  error: No such file or directory
sleep 3

while read casename
do
	note ./run-tests.py $casename
	./run-tests.py $casename 2>&1
done < $group_file
./stop.sh
