#!/bin/bash
# - group

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh

cd "$BENCHMARK_ROOT/igt" || exit

exclude=$BENCHMARK_ROOT/igt/exclude
test_file=$BENCHMARK_ROOT/igt/$group

excluded_tests=$(cat "$exclude" | grep -v "#")

for test in ${excluded_tests[@]}
do
	sed -i "/$test/d" test_file
done

while read testcase
do
	subtests=$(build/tests/$testcase --list-subtest)
	for subtest in ${subtests[@]}
	do
		echo $subtest | grep suspend && continue

		log_cmd build/tests/$testcase --run-subtest $subtest 2>&1

		# #define IGT_EXIT_ABORT 112
		# Exit status indicating a severe test/enviroment failure, any continued
		# testing past this point can yeild unexpected reasults and is not recommended
		[ $? -eq 112 ] && exit 112
	done
done < $test_file
