#!/bin/bash
# - rpm_name
# custom_repo_name
# custom_repo_addr
# user can add custom_repo_name and custom_repo_addr to setup
# local repo, value can be an array

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/log.sh
. $LKP_SRC/lib/rpm.sh

: "${DISTRO:=openeuler}"
: "${basearch:=$(arch)}"
. $LKP_SRC/distro/${DISTRO}

[ -n "${rpm_name}" ]		|| die "rpm_name is empty"
[ -n "${custom_repo_name}" ]	|| die "custom_repo_name is empty"
[ -n "${custom_repo_addr}" ]	|| die "custom_repo_addr is empty"

rpm_name=($rpm_name)

install_rpm()
{
	log_info "Starting install test: yum install -y ${rpm_name[@]}"
	yum install -y "${rpm_name[@]}" 2>&1 || die "install rpm failed"
	echo "install success: ${rpm_name[@]}"
}

ldd_test()
{
	log_info "Starting ldd test"
	for i in $(rpm -qa ${rpm_name[@]})
	do
		ldd_list=$(rpm -ql $i | awk -F'/' '$3 ~ /bin|sbin|lib|lib64/')
		[ -z "${ldd_list}" ] || {
			for i in ${ldd_list[@]}
			do
				[[ -f "$i" && -x "$i" ]] && {
					echo "ldd for $i"
					ldd -d -r $i
				}
			done
		}
	done
}

handle_rpm_name()
{
	local yum_info=$(yum info --installed "$@")
	local name=$(echo "${yum_info}" | awk '{if($1 ~ /Name/) print $3}')
	local version=$(echo "${yum_info}" | awk '{if($1 ~ /Version/) print $3}')
	local release=$(echo "${yum_info}" | awk '{if($1 ~ /Release/) print $3}')
	local architecture=$(echo "${yum_info}" | awk '{if($1 ~ /Architecture/) print $3}')

	rpm_full_name="${name}-${version}-${release}.${architecture}"
}

remove_rpm()
{
	for i in ${rpm_name[@]}
	do
		handle_rpm_name $i
		echo "start remove test: ${rpm_full_name}"
		yum remove -y "$i" 2>&1
		echo "remove test finished: ${rpm_full_name}"
	done
}

distro_install_depends install-rpm
add_repo
install_rpm
ldd_test
remove_rpm
