#!/bin/sh
# - block_size
# - file_size
# - write_rewrite
# - read_reread
# - random_read_write
# - read_backwards
# - rewrite_record
# - stride_read
# - fwrite_refwrite
# - fread_refread
# - random_mix
# - pwrite_repwrite
# - pread_repread
# - pwritev_repwritev
# - preadv_repreadv
## IOzone is a filesystem benchmark tool. The benchmark generates
## and measures a variety of file operations.

. $LKP_SRC/lib/reproduce-log.sh


args="iozone"
if [ -n "$block_size" ]; then
	args+=" -r $block_size"
	[ -n "$file_size" ]         && args+=" -s $file_size"
	[ -n "$write_rewrite" ]     && args+=" -i 0"
	[ -n "$read_reread" ]       && args+=" -i 1"
	[ -n "$random_read_write" ] && args+=" -i 2"
	[ -n "$read_backwards" ]    && args+=" -i 3"
	[ -n "$rewrite_record" ]    && args+=" -i 4"
	[ -n "$stride_read" ]       && args+=" -i 5"
	[ -n "$fwrite_refwrite" ]   && args+=" -i 6"
	[ -n "$fread_refread" ]     && args+=" -i 7"
	[ -n "$random_mix" ]        && args+=" -i 8"
	[ -n "$pwrite_repwrite" ]   && args+=" -i 9"
	[ -n "$pread_repread" ]     && args+=" -i 10"
	[ -n "$pwritev_repwritev" ] && args+=" -i 11"
	[ -n "$preadv_repreadv" ]   && args+=" -i 12"
else
	args+=" -a"
fi

for mnt in $mount_points
do
	cmd="${args} -f $mnt/iozonetest"
	log_echo "$cmd &"
	$cmd > $TMP/iozone-$i &
	i=$((i+1))
done

log_eval wait

cat $TMP/iozone-*
