#!/bin/sh
# - runtime
# - protocol

[ -n "$runtime" ] || runtime=300
[ "$protocol" = udp ] && opt_udp=-u

client_cmd="iperf3 -t $runtime -f M -J -c 127.0.0.1 $opt_udp"

echo "$(date +'%F %T') ${client_cmd}" >> $RESULT_ROOT/reproduce.sh
${client_cmd}
