#!/bin/sh
#

cd $BENCHMARK_ROOT/kernel_selftests || exit

# workaround hugetlbfstest.c open_file() error
mkdir -p /hugepages

# has too many errors now
sed -i 's/hugetlbfstest//' vm/Makefile

for mf in */Makefile; do
	subtest=${mf%/Makefile}
	[ "$subtest" = net ] && continue
	[ "$subtest" = user ] && continue
	[ "$subtest" = sysctl ] && continue
	[ "$subtest" = efivarfs ] && continue
	[ "$subtest" = firmware ] && continue
	[ "$subtest" = memory-hotplug ] && continue
	[ "$subtest" = memfd ] && continue
	cmd make run_tests -C $subtest
done
