#!/bin/sh
#

cd $BENCHMARK_ROOT/kernel_selftests || exit

# workaround hugetlbfstest.c open_file() error
mkdir -p /hugepages

# has too many errors now
sed -i 's/hugetlbfstest//' vm/Makefile

for mf in */Makefile; do
	subtest=${mf%/Makefile}
	case $subtest in
		efivarfs)
			[ -d /sys/firmware/efi ] || {
				echo skip efivarfs test: /sys/firmware/efi dir does not exist
				continue
			}
			grep -q -F -w efivarfs /proc/filesystems || modprobe efivarfs || {
				echo skip efivarfs test: no efivarfs support, try enable CONFIG_EFIVAR_FS
				continue
			}
			mount -t efivarfs efivarfs /sys/firmware/efi/efivars
			;;
	esac
	cmd make run_tests -C $subtest
done
