#!/bin/bash

## The kernel contains a set of "self tests" under the tools/testing/selftests/
## directory. These are intended to be small unit tests to exercise individual
## code paths in the kernel.
## See: https://www.kernel.org/doc/Documentation/kselftest.txt

cd $BENCHMARK_ROOT/kernel_selftests || exit

# workaround hugetlbfstest.c open_file() error
mkdir -p /hugepages

# has too many errors now
sed -i 's/hugetlbfstest//' vm/Makefile

# linux-headers file is created by 0day system for each x86_64-rhel kernel, and located in /usr/src/linux-headers-$kconfig-$commit directory.
shopt -s nullglob
linux_headers_dirs=(/usr/src/linux-headers*)

[[ $linux_headers_dirs ]] || {
	echo "KERNEL SELFTESTS: fail to find linux-headers package" >&2
	exit
}

linux_headers_dir=${linux_headers_dirs[-1]}
echo "KERNEL SELFTESTS: linux_headers_dir is $linux_headers_dir"

for mf in */Makefile; do
	subtest=${mf%/Makefile}
	case $subtest in
		efivarfs)
			[ -d /sys/firmware/efi ] || {
				echo skip efivarfs test: /sys/firmware/efi dir does not exist
				continue
			}
			grep -q -F -w efivarfs /proc/filesystems || modprobe efivarfs || {
				echo skip efivarfs test: no efivarfs support, try enable CONFIG_EFIVAR_FS
				continue
			}
			mount -t efivarfs efivarfs /sys/firmware/efi/efivars
			;;
	esac
	cmd make run_tests -C $subtest -I $linux_headers_dir/include -I $linux_headers_dir/include/uapi
done
