#!/bin/sh
# - runtime

## Measuring latency in the Linux network stack between kernel and user space.

. $LKP_SRC/lib/reproduce-log.sh

cd $BENCHMARK_ROOT/ku-latency || die "no $BENCHMARK_ROOT/ku-latency"

[ -n "$runtime" ] || runtime=300

./ku-latency -e localhost &
LATENCY_PID=$!

./send-data -d localhost &
DATA_PID=$!

sleep $runtime

kill -INT $DATA_PID
kill $LATENCY_PID
