#!/bin/bash

. $LKP_SRC/lib/reproduce-log.sh

test_array=("bitfield_kunit" "cmdline_kunit" "ext4-inode-test" "kunit" "mptcp_crypto_test" "mptcp_token_test" "resource_kunit" "sysctl-test" "test_bits" "test_linear_ranges" "list-test")

run_kunit_tests()
{
	for i in ${test_array[@]}; do
		log_cmd modprobe $i
		log_cmd rmmod $i
	done
}

run_kunit_tests
dmesg > "$TMP_RESULT_ROOT"/kunit
