#!/bin/bash

cd $BENCHMARK_ROOT/kvm-unit-tests || exit

[ -c '/dev/kvm' ] || modprobe kvm_intel

cmd ./run_tests.sh || {
	exit_code=$?

	# dump debug info
	ldd /usr/bin/qemu-system-x86_64
	lsmod
	exit $exit_code
}

chmod g+w	$BENCHMARK_ROOT/kvm-unit-tests/test.log
chown lkp.lkp	$BENCHMARK_ROOT/kvm-unit-tests/test.log
cp -a		$BENCHMARK_ROOT/kvm-unit-tests/test.log $RESULT_ROOT/
