#!/bin/sh
# - pagesize
# - pagenum

. $LKP_SRC/lib/debug.sh

cd $BENCHMARK_ROOT/libhugetlbfs-test || die "can not cd libhugetlbfs-test"

log_cmd make || die "make failed"

[ -z $pagesize -o -z $pagenum ] && die "invalid parameter"

# in order to config huge pages size and number
log_cmd obj/hugeadm --add-temp-swap=$pagenum --pool-pages-min $pagesize:$pagenum --hard \
	|| die "config huge pages size and number failed"

log_cmd make check

# replace the full-width characters with half-width to avoid the stderr.json
# eg.
# before sed: shmoverride_unlinked.c: In function ‘local_read_meminfo’:
# after sed: shmoverride_unlinked.c: In function 'local_read_meminfo':
[ -s $TMP/stderr ] && sed -i "s/‘\|’/'/g" $TMP/stderr
