#!/bin/sh

cd $BENCHMARK_ROOT/linpack || exit

. $LKP_SRC/lib/unit.sh

export memory_bytes=$(to_byte $memory)

max_mem=$((32<<30))
[ "$memory_bytes" -gt "$max_mem" ] && memory_bytes=$max_mem

dimension=$(echo "sqrt ($memory_bytes * 0.9 / 8)" | bc)

cat > lininput_xeon64 <<EOF
Sample Intel(R) Optimized LINPACK Benchmark data file (lininput_xeon64)
Intel(R) Optimized LINPACK Benchmark data
1		# number of tests
$dimension	# problem sizes
$dimension	# leading dimensions
1		# times to run a test
4		# alignment values (in KBytes)"
EOF

cmd ./runme_xeon64
