#!/bin/sh
# - runtime

## The tests periodically output status messages via printk(),
## which can be examined via the dmesg (perhaps grepping for "torture")
## The test is started when the module is loaded, and stops when the module is unloaded.

. $LKP_SRC/lib/debug.sh

modprobe locktorture || die "failed to load locktorture module"

sleep $runtime

rmmod locktorture
