#!/bin/sh
# - runtime

## The tests periodically output status messages via printk(),
## which can be examined via the dmesg (perhaps grepping for "torture")
## The test is started when the module is loaded, and stops when the module is unloaded.

. $LKP_SRC/lib/debug.sh

log_cmd modprobe locktorture ||
die "failed to load locktorture module, try to enable CONFIG_LOCK_TORTURE_TEST and build locktorture.ko"

log_cmd sleep $runtime

log_cmd rmmod locktorture
