#!/bin/sh
# - test

cd $BENCHMARK_ROOT/ltp || exit

if [ "$test" = 'dio' ]; then
	[ -z "$mount_points" ] && exit
	export TMPDIR=$(echo $mount_points | cut -d' ' -f1)
fi

cmd ./runltp -f $test

mkdir $RESULT_ROOT/ltp-results
for dir in results output
do
	chmod g+w	$BENCHMARK_ROOT/ltp/$dir/*
	chown lkp.lkp	$BENCHMARK_ROOT/ltp/$dir/*
	cp -a		$BENCHMARK_ROOT/ltp/$dir/* $RESULT_ROOT/ltp-results
done
