#!/bin/bash
# - pkgname

cd $LKP_SRC/pkg/$pkgname || exit

[ -n "$LKP_SERVER" ] && {
	mount $LKP_SERVER:/pkg /pkg || exit
}

sudo -E -u lkp \
	PACMAN=true BUILDDIR=$TMP PKGEXT=.cgz \
	$LKP_SRC/sbin/makepkg --config $LKP_SRC/etc/makepkg.conf
