#!/bin/bash
# - pkgname

## makepkg is a script that automates the building of packages; it can download and validate source files,
## check dependencies, configure build-time settings, compile the sources, install into a temporary root,
## make customizations, generate meta-info, and package everything together.
## See: https://wiki.archlinux.org/index.php/Makepkg

cd $LKP_SRC/pkg/$pkgname || exit

[ -n "$LKP_SERVER" ] && {
	mount $LKP_SERVER:/pkg /pkg || exit
}

sudo -E -u lkp \
	PACMAN=true BUILDDIR=$TMP PKGEXT=.cgz \
	$LKP_SRC/sbin/makepkg --config $LKP_SRC/etc/makepkg.conf
