#!/bin/bash

## It is always a good idea to test an error handling mechanism before it is really needed.
## mcelog includes a test suite.
## The test suite relies on mce-inject which needs to be installed and in $PATH.

shopt -s nullglob

. $LKP_SRC/lib/debug.sh

cd $BENCHMARK_ROOT/mce-log || die "can not find mce-log dir"

# workaround this error: '.depend: No such file or directory'
touch .depend

# skip test/socket case, because it requires hardware register CMCI support
# match start with "\t./test socket*"
sed -i '/.*\.\/test socket*/d' tests/Makefile
make test
exit_value=$?

files=($BENCHMARK_ROOT/mce-log/tests/*/results)
if [[ $files ]]; then
    for file in ${files[@]}
    do
        item=`dirname $file`
        echo "mce-log-item:${item##*/}"
        cat $file
    done
else
    echo "WARNING: mcelog test results is not exist."
fi

exit $exit_value
