#!/bin/sh

## The MCE test suite is a collection of tools and test scripts for
## testing the Linux RAS related features, including CPU/Memory
## error containment and recovery, ACPI/APEI support etc.

cd $BENCHMARK_ROOT/mce-test || exit

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/job.sh
read_env_vars

echo > ./work/rastest.caselist <<EOF
APEI-INJ cases/function/apei-inj/runtest.sh
ERST-INJ cases/function/erst-inject/runtest.sh
PFA cases/function/pfa/runtest.sh
HWPOISON-SOFT cases/function/hwpoison/run_soft.sh
HWPOISON-HARD cases/function/hwpoison/run_hard.sh
HWPOISON-HUGEPAGE cases/function/hwpoison/run_hugepage.sh
HWPOISON-HUGEPAGE-OVERCOMMIT cases/function/hwpoison/run_hugepage_overcommit.sh
HWPOISON-THP cases/function/hwpoison/run_thp.sh
BSP cases/function/bsp/runtest.sh
STRESS-HWPOISON-SOFT cases/stress/hwpoison/run_soft.sh
STRESS-HWPOISON-HARD cases/stress/hwpoison/run_hard.sh
EOF

./runmcetest -t ./work -s ./summary -o ./results -b ./bin -l ./work/rastest.caselist -r 1

[ "$nr_partitions" -ge 1 ] || exit
partition=${partitions%% *}

[ -n "$duration" ] || duration=60

cd cases/stress/hwpoison || exit

# the latter hwpoison.sh script will call LTP project which will remove $TMP after run finished.
# currently, the variable TMP=/tmp/lkp contain various log file, so need to export TMP variable to temp dir.
tmp_dir=$(mktemp -d /tmp/mce-test-XXXXXX) || exit
export TMP=$tmp_dir

export TERM=linux # to quiet stderr message "TERM environment variable not set."

umount $partition
wipefs -a $partition
echo y | ./hwpoison.sh -c /dev/null -t $duration -d $partition -o $BENCHMARK_ROOT/mce-test/ltp -f $fs -L 2>&1
exit_value=$?

## currently, always can not pass this testing, so disable it temporarily.
#if [ "$exit_value" = "0" ]; then
#	wipefs -a $partition
#	echo y | ./hwpoison.sh -c /dev/null -t $duration -d $partition -o $BENCHMARK_ROOT/mce-test/ltp -f $fs -M 2>&1
#	exit_value=$?
#fi

upload_files -t results $BENCHMARK_ROOT/mce-test/cases/stress/hwpoison/log \
	$BENCHMARK_ROOT/mce-test/cases/stress/hwpoison/result

rm -fr "$tmp_dir"

exit $exit_value
