#!/bin/sh
# - test_prefix

## mdadm is a tool for managing Linux Software RAID arrays.

cd $BENCHMARK_ROOT/mdadm-selftests || exit 1

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/debug.sh

[ -n "$test_prefix" ] || die "test_prefix is emtpy"

# https://raid.wiki.kernel.org/index.php/RAID_setup
modprobe raid0
modprobe raid1
modprobe raid10
modprobe raid456

modprobe loop

run_test()
{
	# sub-case "11" typicall need to cost ~15m.
	if [ "$test_prefix" = "11" ]; then
		timeout 20m ./test "--tests=$testcase"
	else
		timeout 5m ./test "--tests=$testcase"
	fi

	[ $? -eq 124 ] && echo "$testcase TIMEOUT"

	local res_dir="result/$testcase"
	mkdir -p  $res_dir
	cp /var/tmp/log $res_dir
}

for testcase in $(cd tests && ls ${test_prefix}*); do
	run_test
done

exit_value=$?

upload_files -t results result/*

exit $exit_value
