#!/bin/sh


##MongoDB is a document database with the scalability and flexibility
##that you want with the querying and indexing that you need

. $LKP_SRC/lib/reproduce-log.sh

export PATH=$BENCHMARK_ROOT/mongodb/mongodb/bin:$PATH

#mongodb server run as daemon, so do nothing here
