#!/bin/bash

## Utility library for managing the Linux Kernel ND (NFIT-defined/NVDIMM) Subsystem
## detailed info can refer to https://github.com/pmem/ndctl

shopt -s nullglob

. $LKP_SRC/lib/debug.sh

[[ -x "/lkp/benchmarks/ndctl/bin/ndctl" ]] || die "Can not find executable ndctl file"

[[ -d /etc/depmod.d ]] || log_cmd mkdir -p /etc/depmod.d
cat >/etc/depmod.d/nfdtl.conf <<EOF
override nfit * extra
override dax * extra
override dax_pmem * extra
override libnvdimm * extra
override nd_blk * extra
override nd_btt * extra
override nd_e820 * extra
override nd_pmem * extra
EOF

LD_LIBRARY_PATH=/lkp/benchmarks/ndctl/lib \
/lkp/benchmarks/ndctl/bin/ndctl test
