#!/bin/bash

## Utility library for managing the Linux Kernel ND (NFIT-defined/NVDIMM) Subsystem
## detailed info can refer to https://github.com/pmem/ndctl

shopt -s nullglob

. $LKP_SRC/lib/debug.sh

[[ -x "/lkp/benchmarks/ndctl/bin/ndctl" ]] || die "Can not find executable ndctl file"

LD_LIBRARY_PATH=/lkp/benchmarks/ndctl/lib \
/lkp/benchmarks/ndctl/bin/ndctl test
