#!/bin/sh
# - runtime
# - nr_threads
# - test
# - send_size

export PATH=$BENCHMARK_ROOT/netperf/bin:$PATH

[ "${test#*SCTP}" != "$test" ] && modprobe sctp 2>/dev/null
sleep 1

[ -n "$send_size" ] && test_options="-- -m $send_size"

for i in $(seq $nr_threads)
do
	cmd netperf -t $test -c -C -l $runtime $test_options &
done

wait
