#!/bin/bash
# - test
# - group

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/nvml.sh

check_param "$testcase"

fixup_valgrind

build_env "$testcase" || die "build env failed"

enable_remote_node "$testcase"

run "$testcase"
