#!/bin/sh

## The packetdrill scripting tool enables quick, precise tests for
## entire TCP/UDP/IPv4/IPv6 network stacks, from the system call
## layer down to the NIC hardware.

cd $BENCHMARK_ROOT/packetdrill || exit

# fix the issue: open tun device: No such file or directory
lsmod | grep -q tun || modprobe tun

for f in $(find . -name "*.pkt" ! -name "*diag-ipv6*" | sort); do
	echo "Running $f ..."
	ip tcp_metrics flush all > /dev/null 2>&1
	log_cmd ./gtests/net/packetdrill/packetdrill $f
	return_value=$?
	if [ $return_value -eq 0 ]; then
		echo "$f pass"
	else
		echo "$f failed"
	fi
done
