#!/bin/sh
# - paranoid

## perf_event_tests is designed to test trinity for perf
## See: https://github.com/deater/perf_event_tests

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/perf_event_tests.sh

cd $BENCHMARK_ROOT/perf_event_tests || die "can not find perf_event_test dir"

check_elements "$paranoid"
setup_test_env "$paranoid"

log_cmd ./run_tests.sh

cleanup_test_env
