#!/bin/bash
# - paranoid

## perf_event_tests is designed to test trinity for perf
## See: https://github.com/deater/perf_event_tests

. $LKP_SRC/lib/debug.sh

[[ "$paranoid" ]] || die "parameter \"paramoid\" is empty"

cd $BENCHMARK_ROOT/perf_event_tests || die "can not find perf_event_test dir"

perf_event_paranoid="/proc/sys/kernel/perf_event_paranoid"

[[ -e "$perf_event_paranoid" ]] || die "can not find file $perf_event_paranoid"
paranoid_value_old=`cat $perf_event_paranoid`

case "$paranoid" in
    not_paranoid_at_all)        paranoid_value=-1 ;;
    disallow_raw_tracepoint)    paranoid_value=0  ;;
    disallow_cpu_events)        paranoid_value=1  ;;
    disallow_kernel_profiling)  paranoid_value=2  ;;
esac

echo $paranoid_value > $perf_event_paranoid

[[ $paranoid_value = $(cat $perf_event_paranoid) ]] || die "write value $paranoid_value to $perf_event_paranoid failed"

unstable_cases="flags_fd_no_group simultaneous_overflow context_switch_user_kernel rdpmc_multiattach openmp_sample
                check_multiplexing rdpmc_multiattach_papi rdpmc_validation"

for unstable in $unstable_cases
do
	grep -w -q "$unstable$" ./run_tests.sh && echo "ignored_by_lkp $unstable" && sed -i /$unstable$/d ./run_tests.sh
done

fixup_old_platform()
{
	# FIXME: Model number: snb: 42, ivb: 58, haswell: 60, skl: 94
	local haswell=60
	local ignored="fixed_ctr0"
	local model=$(lscpu | grep 'Model:' | awk '{print $2}')
	[[ -z "$model" ]] && return
	[[ $model -lt $haswell ]] || return
	grep -w -q "$ignored$" ./run_tests.sh && echo "ignored_by_lkp $ignored" && sed -i /$ignored$/d ./run_tests.sh
}

# eaccess will fail if paranoid_value in [1,2], so run eacces under lkp
[[ $paranoid_value -gt 0 ]] && sed -i -e 's/\$TESTS_DIR\/error_returns\/eacces/su lkp -c \"\$TESTS_DIR\/error_returns\/eacces\"/g' ./run_tests.sh

fixup_old_platform

log_cmd ./run_tests.sh
exit_value=$?

echo $paranoid_value_old > $perf_event_paranoid

[[ $paranoid_value_old = $(cat $perf_event_paranoid) ]] || echo "Warning: write value $paranoid_value_old to $perf_event_paranoid failed"

exit $exit_value
