#!/bin/sh
# - nr_threads
# - mem_proc

## perf began as a tool for using the performance counters
## subsystem in Linux, and has had various enhancements
## to add tracing capabilities.

. $LKP_SRC/lib/unit.sh

mb_proc=$(to_mb $mem_proc)

cmd perf bench numa mem -p $nr_cpu -t $nr_threads -m -0 -P $mb_proc
