#!/bin/bash
# - group

export PATH=$BENCHMARK_ROOT/piglit/bin:$PATH
export DISPLAY=:0

dri_exist()
{
	[[ -d /sys/kernel/debug/dri ]]
}

check_wait_dri()
{
	dri_exist && return

	mountpoint /sys/kernel/debug ||
	mount -t debugfs debugfs /sys/kernel/debug || exit

	dri_exist && return

	modprobe drm

	for i in {1..9}
	do
		sleep $i
		dri_exist && return
	done

	dri_exist && return

	echo "No /sys/kernel/debug/dri" >&2
}

check_wait_dri

tset=${group%%-*}
testcases=()
while read testcase
do
	testcases+=( "$testcase" )
done <<< "$(grep -F -x -f $BENCHMARK_ROOT/piglit/groups/$tset-all $BENCHMARK_ROOT/piglit/groups/$group)"

for testcase in "${testcases[@]}"
do
	start_time=$(date +%s)
	cmd piglit run $tset -t "$testcase" $RESULT_ROOT/$tset
	end_time=$(date +%s)
	echo test time "$testcase": $(( end_time - start_time ))

	cmd piglit summary console $RESULT_ROOT/$tset
done
