#!/bin/sh
# - test

# Utilities for testing Power Management

cd $BENCHMARK_ROOT/pm-qa || exit

run_one()
{
	local testcase=$1
	if [ "$testcase" = 'cpuhotplug' ]; then
		ext_opt='hotplug_allow_cpu0=0'
	else
		ext_opt=
	fi

	cmd make -C $testcase $ext_opt run_tests

	copy-results $BENCHMARK_ROOT/pm-qa/$testcase/*.log
}

if [ "$test" = 'all' ]; then
	for i in cpufreq cpuhotplug cputopology cpuidle thermal
	do
		run_one $i
	done
else
	run_one $test
fi
