#!/bin/sh
# - runtime
# - pattern
# - mapsize
# - setsize
# - shape
# - nr_processes
# - nr_threads
# - timestamp
# - cold
# - access
# - delay
# - initialize
# - offset
# - quiet
# - ratio
# - threshold

. "$LKP_SRC/lib/common.sh"
. "$LKP_SRC/lib/reproduce-log.sh"

: "${runtime:=300}"
: "${nr_processes:=1}"

set_opt()
{
	opt=
	if [ -n "$setsize" ]; then
		opt="${opt} -s$((setsize/1024/1024))"
		[ -z "$mapsize" ] && mapsize="$setsize"
	fi
	[ -n "$mapsize" ] && opt="${opt} -m$((mapsize/1024/1024))"
	[ -n "$pattern" ] && opt="${opt} -p${pattern}"
	[ -n "$shape" ] && opt="${opt} -e${shape}"
	[ -n "$nr_threads" ] && opt="${opt} -j${nr_threads}"
	[ -n "$timestamp" ] && opt="${opt} -t${timestamp}"
	parse_bool -q "$cold" && opt="${opt} -c"
	[ -n "$access" ] && opt="${opt} -a${access}"
	[ -n "$delay" ] && opt="${opt} -d${delay}"
	parse_bool -q "$initialize" && opt="${opt} -i"
	[ -n "$offset" ] && opt="${opt} -o${offset}"
	parse_bool -q "$quiet" && opt="${opt} -q"
	[ -n "$ratio" ] && opt="${opt} -r${ratio}"
	[ -n "$threshold" ] && opt="${opt} -h${threshold}"
}

set_opt

pmb_tmp_dir="$TMP/pmbench"
rm -rf "$pmb_tmp_dir"
mkdir -p "$pmb_tmp_dir"

for i in $(seq 1 $nr_processes); do
	log_echo "$exec_prefix /usr/local/bin/pmbench $opt $runtime > $pmb_tmp_dir/pmbench.$i &"
	/usr/local/bin/pmbench $opt $runtime > "$pmb_tmp_dir/pmbench.$i" &
done

wait

cat "$pmb_tmp_dir"/pmbench.*
