#!/bin/sh
# - runtime
# - pattern
# - mapsize
# - shape
# - nr_threads
# - timestamp
# - cold
# - access
# - delay
# - initialize
# - offset
# - quiet
# - ratio
# - threshold

. "$LKP_SRC/lib/common.sh"

[ -n "$runtime" ] || runtime=60

set_opt()
{
	opt=
	if [ -n "$setsize" ]; then
		opt="${opt} -s$((setsize/1024/1024))"
		[ -z "$mapsize" ] && mapsize="$setsize"
	fi
	[ -n "$mapsize" ] && opt="${opt} -m$((mapsize/1024/1024))"
	[ -n "$pattern" ] && opt="${opt} -p${pattern}"
	[ -n "$shape" ] && opt="${opt} -e${shape}"
	[ -n "$nr_threads" ] && opt="${opt} -j${nr_threads}"
	[ -n "$timestamp" ] && opt="${opt} -t${timestamp}"
	parse_bool -q "$cold" && opt="${opt} -c"
	[ -n "$access" ] && opt="${opt} -a${access}"
	[ -n "$delay" ] && opt="${opt} -d${delay}"
	parse_bool -q "$initialize" && opt="${opt} -i"
	[ -n "$offset" ] && opt="${opt} -o${offset}"
	parse_bool -q "$quiet" && opt="${opt} -q"
	[ -n "$ratio" ] && opt="${opt} -r${ratio}"
	[ -n "$threshold" ] && opt="${opt} -h${threshold}"
}

run_pmbench()
{
	log_cmd /usr/local/bin/pmbench $opt $runtime
}

set_opt

run_pmbench
