#!/bin/sh
# - number
# - trans
# - subdirs

## File system benchmark from NetApp.
## Benchmark that's based around small file operations similar to those
## used on large mail servers and news servers. Has been ported to NT
## so should be good for comparing OSs. "Postmark: a new file system
## benchmark", Jeffrey Katcher, Network Appliance Technical Report TR-3022, October 1997

. $LKP_SRC/lib/reproduce-log.sh

[ -z "$mount_points" ] && die "no $mount_points"

location="${mount_points%% *}"
number=${number%n}
trans=${trans%s}
subdirs=${subdirs%d}

log_cmd postmark <<EOF
set size 10000 20000
set number $number
set transactions $trans
set subdirectories $subdirs
set location $location
set report terse
show
run
EOF
