#!/bin/sh
# - runtime

## creates an rcutorture kernel module that can be loaded to
## run a torture test.

. $LKP_SRC/lib/debug.sh

log_cmd modprobe rcutorture || die "failed to load rcutorture module"

log_cmd sleep $runtime

log_cmd rmmod rcutorture 2> /dev/null

dmesg | grep torture:
