#!/bin/sh
# - runtime

## creates an rcutorture kernel module that can be loaded to
## run a torture test.

. $LKP_SRC/lib/debug.sh

modprobe rcutorture || die "failed to load rcutorture module"

sleep $runtime

rmmod rcutorture 2> /dev/null

dmesg | grep torture:
