#!/bin/sh
# - test
# - nr_task
# - nr_job
# - iterations

## REAIM is an updated and improved version of AIM 7 benchmark. It
## forks many processes called tasks, each of which concurrently runs
## in random order a set of subtests called jobs.  Each job exercises
## a different aspect of the operating system, such as disk-file
## operations, process creation, user virtual memory operations, pipe
## I/O, and compute-bound arithmetic loops.
##
## Homepage: https://sourceforge.net/projects/re-aim-7/

iterations=${iterations:-1}
nr_job=${nr_job:-100}

cd $BENCHMARK_ROOT/reaim || exit

if [ -z "$nr_task" ]; then
	REAIM_STARTUSERS=1
	REAIM_ENDUSERS=$((nr_cpu*4))
	REAIM_INCREMENT=$((nr_cpu/4))
	[ "$REAIM_INCREMENT" = 0 ] && REAIM_INCREMENT=1
else
	REAIM_STARTUSERS=$nr_task
	REAIM_ENDUSERS=$nr_task
	REAIM_INCREMENT=$nr_task
fi

REAIM_FILESIZE=10k
REAIM_POOLSIZE=1m
# setup config file
if [ -n "$mount_points" ]; then
	REAIM_TESTDIR="${mount_points%% *}"
else
	mkdir -p /fs/shm
	umount /fs/shm > /dev/null 2>&1
	mount -t tmpfs tmpfs /fs/shm
	REAIM_TESTDIR="/fs/shm"
fi

echo FILESIZE $REAIM_FILESIZE > reaim.config
echo POOLSIZE $REAIM_POOLSIZE >> reaim.config
echo DISKDIR $REAIM_TESTDIR  >> reaim.config

cmd ./reaim -s$REAIM_STARTUSERS -e$REAIM_ENDUSERS -i$REAIM_INCREMENT -fdata/workfile.$test \
	-r$iterations -c./reaim.config -l$TMP_RESULT_ROOT/reaim_debug -j$nr_job |
	grep -v -e "^NSIG is "
