#!/bin/sh
# - test
# - data_size
# - n_client
# - requests
# - n_pipeline
# - key_len
# - nr_task
# - enable_numa_bind

## Redis is an open source (BSD licensed), in-memory data structure store,
## used as a database, cache and message broker. It supports data structures
## such as strings, hashes, lists, sets, sorted sets with range queries,
## bitmaps, hyperloglogs, geospatial indexes with radius queries and streams.
## Redis includes the redis-benchmark utility that simulates running commands
## done by N clients at the same time sending M total queries (it is similar
## to the Apache's ab utility)

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/common.sh
export PATH=$BENCHMARK_ROOT/redis/bin:$PATH
for i in $(seq 1 "${nr_task}")
do
	port=$((6379+$i))
	if parse_bool -q "$enable_numa_bind"; then
		bind=$(($i%2))
		numa_bind="numactl --cpunodebind=$bind --"
	fi
	log_test $numa_bind redis-benchmark -t $test -d $data_size -c $n_client -n $requests -P $n_pipeline -r $key_len -p $port&
done
wait
