#!/bin/bash
# - upstream_repo
# - compat_os

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh

: "${compat_os:=budding-openeuler}"

[ -n "$upstream_repo" ] || die "upstream_repo is empty"
package_name=${upstream_repo##*/}
rpm_dest="/initrd/rpmbuild-pkg/${os}-${os_version}/${compat_os}/${os_arch}/Packages"
src_rpm_dest="/initrd/rpmbuild-pkg/${os}-${os_version}/${compat_os}/source/Packages"

init_workspace()
{
	# generate workspace in ${HOME}
	rpmdev-setuptree
}

download_upstream_repo()
{
	git clone "git://$GIT_SERVER/openeuler/${upstream_repo}" || die "clone git repo ${package_name} failed: git://$GIT_SERVER/openeuler/${upstream_repo}"
	cd $package_name || exit
	filelist=$(git ls-files)
	for pkgfile in ${filelist[@]}
	do
		local dir="SOURCES"
		echo $pkgfile | egrep "\.spec$" && dir="SPECS"
		mv "$pkgfile" "${HOME}/rpmbuild/${dir}/"
	done
}

build_rpm()
{
	local spec_file=${HOME}/rpmbuild/SPECS/$package_name.spec

	# HTTP is proxy cache friendly
	sed -i 's/^\(Source[^ ]*:[ \t]*\)https/\1http/g' `grep http -rl $spec_file`

	# Install build depends
	yum-builddep -y $spec_file || exit
	# Download tar.gz to default path ${HOME}/rpmbuild/SOURCE
	spectool -g -R $spec_file || exit
	# Building rpm or srpm packages
	rpmbuild -ba $spec_file || exit
}

show_rpm_files()
{
	find ${HOME}/rpmbuild/RPMS -type f -name "*.rpm"
}

show_src_rpm_files()
{
	find ${HOME}/rpmbuild/SRPMS -type f -name "*.rpm"
}

upload_rpm_pkg()
{
	local rpm_file
	for rpm_file in $(show_rpm_files)
	do
		upload_one_curl ${rpm_file} ${rpm_dest}
	done

	local src_rpm_file
	for src_rpm_file in $(show_src_rpm_files)
	do
		upload_one_curl ${src_rpm_file} ${src_rpm_dest}
	done
}

init_workspace
download_upstream_repo
build_rpm
upload_rpm_pkg
