#!/bin/sh
# - workload

. $LKP_SRC/lib/upload.sh

cd $BENCHMARK_ROOT/rt-app || {
	echo "ERROR: rt-app benchmark is not installed yet!" >&2
	exit 1
}

log_cmd bin/rt-app workloads/${workload}.json 2>&1
exit_value=$?

log_cmd find . -print -name "*.log" -exec cat {} \;

upload_files -t results $BENCHMARK_ROOT/rt-app/*.log
exit $exit_value
