#!/bin/bash

. $LKP_SRC/lib/email.sh
. $LKP_SRC/lib/log.sh
. $LKP_SRC/lib/upload.sh

source /etc/profile.d/compass.sh

group_id=selftest

cci_makepkg=(	reaim
		pixz
		iozone
		hackbench
		netpipe
		pft
		ku-latency
		redis-server
		hackben-git
)

cci_depends=(	sshd
		pft
		reaim
		pixz
		netpipe
		numactl
		fs
)

dc_cases=(	"testbox=dc-8g borrow-1h.yaml runtime=10s"	)

vm_cases=(	"testbox=vm-2p8g borrow-1h.yaml     runtime=10s"
		"testbox=vm-2p8g reaim.yaml         reaim.test=aim9 runtime=10s"
		"testbox=vm-2p8g pixz.yaml          nr_threads=100% runtime=10s"
		"testbox=vm-2p8g iozone-bs.yaml     block_size=64k  runtime=10s"
		"testbox=vm-2p8g hackbench-git.yaml nr_threads=1    hackbench-git.mode=process hackbench-git.ipc=pipe runtime=10s"
		"testbox=vm-2p8g host-info.yaml     runtime=10s"
		"testbox=vm-2p8g kunit.yaml         runtime=10s"
		"testbox=vm-2p8g netpipe.yaml       runtime=10s"
		"testbox=vm-2p8g redis.yaml         runtime=10s"
		"testbox=vm-2p8g ku-latency.yaml    runtime=10s"
		"testbox=vm-2p8g pft.yaml           nr_task=50%     runtime=10s"
)

run_testboxes()
{
	"$CCI_SRC"/providers/multi-qemu -n vm-2p16g -c 5 -q vm-2p16g."$(arch)" >/dev/null 2>&1 &
}

submit_makepkg()
{
	local testbox=vm-2p16g

	for args in "${cci_makepkg[@]}"
	do
		submit -m testbox="$testbox" cci-makepkg.yaml cci-makepkg.benchmark="$args" group_id="$group_id" >/dev/null 2>&1 &
	done
}

submit_depends()
{
	local testbox=vm-2p8g

	for args in "${cci_depends[@]}"
	do
		submit -m testbox="$testbox" cci-depends.yaml cci-depends.benchmark="$args" group_id="$group_id" >/dev/null 2>&1 &
	done
}

submit_cases()
{
	for args in "${vm_cases[@]}" "${dc_cases[@]}"
	do
		submit -m $args group_id="$group_id" >/dev/null 2>&1 &
	done
}

get_report_content()
{
	report_content=$(es-jobs group_id="$group_id" | grep job_state)
	log_info "selftest job result: $report_content"
}

get_commit_info()
{
	cd /c/compass-ci || exit

	commit_id=$(git log -1 --format="%H")
	commit_subject=$(git log -1 --format="%s")

	author_name=$(git log -1 --format="%an")
	author_email=$(git log -1 --format="%ae")

	committer=$(git log -1 --format="%cn")
	committer_email=$(git log -1 --format="%ce")

	recipient_email="$author_email;$committer_email"

}

upload_failed_result()
{
	lab=$(awk '/^lab:\s/ {print $2; exit}' /etc/compass-ci/defaults/*.yaml)
	job_ids=$(find /srv/result -name "$lab.*"| awk -F'/' '{print $NF}')
	for job_id in $job_ids
	do
		result_root=/srv$(es-find id=$job_id | grep result_root | cut -d'"' -f4)
		es-find id=$job_id| grep job_state| grep -q finished || upload_files -t $job_id $result_root/*
	done
}

run_testboxes
submit_makepkg
submit_depends
wait

submit_cases
wait

get_commit_info
get_report_content
send_email selftest
upload_failed_result
