#!/bin/bash

. $LKP_SRC/lib/email.sh
. $LKP_SRC/lib/log.sh

source /etc/profile.d/compass.sh

submit_args=(
		"testbox=dc-8g cci-depends.benchmark=sshd cci-depends.yaml"
		"testbox=dc-8g borrow-1h.yaml runtime=1m"
		"testbox=vm-2p8g borrow-1h.yaml runtime=1m"
	    )

submit_job()
{
	for args in "${submit_args[@]}"
	do
		report_content=$(submit -m $args group_id=selftest 2>&1)
		echo $report_content | grep -q "\"job_state\":\"submit\"" ||
			{
				log_error  "submit $args failed: $report_content"
				send_email selftest
				exit 1
			}
	done

	report_content=$(es-jobs group_id=selftest | grep job_state)
	log_info "selftest job result: $report_content"
}

get_commit_info()
{
	cd /c/compass-ci || exit

	commit_id=$(git log -1 --format="%H")
	commit_subject=$(git log -1 --format="%s")

	author_name=$(git log -1 --format="%an")
	author_email=$(git log -1 --format="%ae")

	committer=$(git log -1 --format="%cn")
	committer_email=$(git log -1 --format="%ce")

	recipient_email="$author_email;$committer_email"

}

get_commit_info
submit_job
send_email selftest
