#!/bin/sh
# - runtime
# - msg_size

# sockperf is a tool for network performance measurement

cd $BENCHMARK_ROOT/sockperf || exit

[ -n "$runtime" ] || runtime=600
time=$((runtime / 6))
msg_size=${msg_size%%[bB]}

for subcmd in under-load ping-pong throughput
do
	echo "sockperf: subcommand $subcmd UDP"
	cmd ./sockperf $subcmd --time $time --msg-size $msg_size
	echo "sockperf: subcommand $subcmd TCP"
	cmd ./sockperf $subcmd --time $time --msg-size $msg_size --tcp
done
