#!/bin/sh
# - testtime
# - class
# - nr_threads

[ $nr_partitions -ge 1 ] || exit
partition=${partitions%% *}

mount_dev()
{
	local mnt=/mnt/stress-ng
	log_cmd mkdir -p $mnt
	log_cmd mount $partition $mnt 2>/dev/null
	cd $mnt
}

[ -n "$testtime" ] || testtime=1

[ "$class" = "memory" ] && stress_opts="--minimize" && exlucde_stress=",stack"
[ "$class" = "os" ] && stress_opts="--minimize"
[ "$class" = "filesystem" ] && mount_dev

## most stressors could run as root except exec and spawn, classify exec and spawn into exec_spawn, run it as lkp.
## when we run stress-ng as root, use option --exclude to ignore spawn and exec.
if [ "$class" = "exec_spawn" ]; then
	su lkp -c "stress-ng --exec $nr_threads --spawn $nr_threads --timeout $testtime --times --verify --metrics-brief 2>&1"
else
	stress-ng --sequential $nr_threads --class $class $stress_opts --timeout $testtime --times --verify --metrics-brief --exclude spawn,exec$exlucde_stress 2>&1
fi

