#!/bin/bash
# - iterations

cd $BENCHMARK_ROOT/stutter || exit

memory=${memory/M/*1024*1024}
memory=${memory/G/*1024*1024*1024}
memory=${memory/T/*1024*1024*1024*1024}

export MEMTOTAL_BYTES=$memory
export ITERATIONS=$iterations
export LOGDIR_RESULTS=$RESULT_ROOT/log_result

mkdir -p $LOGDIR_RESULTS

[ -z "$mount_points" ] && exit
export TESTDISK_DIR=$(echo $mount_points | cut -d' ' -f1)

echo "# running ./run.sh..."
./run.sh
if [ $? -ne 0 ]; then
	echo "run_fail: 1"
else
	echo "# run success"
fi
