#!/bin/bash
# - runtime
# - iterations

alarm_path="/sys/class/rtc/rtc0/wakealarm"
[ -f "$alarm_path" ] || exit

[ -n "$runtime" ] || runtime=300
[ -n "$iterations" ] || iterations=30
interval=$(( runtime / iterations ))

for i in `seq 1 $iterations`
do
	echo "+$interval" > $alarm_path
	echo $(date "+%F %T") suspending
	echo freeze > /sys/power/state
	echo $(date "+%F %T") resumed $i
done

echo "SUSPEND RESUME TEST SUCCESS"
