#!/bin/sh
# - runtime
# - nr_threads
# - thread_yields
# - thread_locks

. "$LKP_SRC/lib/reproduce-log.sh"

: "${runtime:=600}"
: "${nr_threads:=1}"
: "${thread_yields:=1000}"
: "${thread_locks:=8}"

args="\
 --threads=$nr_threads\
 --time=$runtime\
 --thread-yields=$thread_yields\
 --thread-locks=$thread_locks\
"
log_cmd sysbench $args threads run
