#!/bin/sh
# mysql_user
# mysql_host
# mysql_port
# mysql_db
# db_driver
# - oltp_test_mode
# - oltp_tables_count
# - oltp_table_size
# - nr_threads
# - runtime
# - report_interval

: "${mysql_user:=root}"
: "${mysql_host:=localhost}"
: "${mysql_port:=3306}"
: "${mysql_db:=test_1000}"
: "${db_driver:=mysql}"
: "${oltp_tables_count:=3}"
: "${oltp_table_size:=1000}"
: "${nr_threads:=64}"
: "${runtime:=120}"
: "${report_interval:=10}"

args=(
	 --mysql-user=$mysql_user
	 --mysql-host=$mysql_host
 	 --mysql-port=$mysql_port
 	 --mysql-db=$mysql_db
	 --db-driver=$db_driver
	 --tables=$oltp_tables_count
	 --table-size=$oltp_table_size
	 --threads=$nr_threads
	 --time=$runtime
	 --report-interval=$report_interval
)

run_sysbench_step()
{
	sysbench /usr/share/sysbench/$1 "${args[@]}" $2
}

run_sysbench_mysql()
{
	systemctl start mysqld
	mysql -e "create database test_1000;"
	run_sysbench_step oltp_common.lua prepare
	run_sysbench_step oltp_read_write.lua run
	run_sysbench_step oltp_common.lua cleanup
}

run_sysbench_mysql
