#!/bin/sh
# - runtime
# - nr_threads

## TBENCH produces the network load to simulate the network part of
## the load of the commecial Netbench benchmark.  Unlike Netbench,
## it doesn't require a lab of Windows PCs:

[ -n "$direct_server_ips" ] && server=$direct_server_ips
[ -z "$server" ] && server=127.0.0.1
[ -n "$runtime" ] || runtime=600
server=${server%% *}

log_cmd tbench -t $runtime $nr_threads $server
