#!/bin/sh
# - modes
# - period

## tcrypt.ko module purpose is to test different crypto algorithm from the kenrel space.

for i in $(seq ${modes%-*} ${modes#*-})
do
	# tcrypt do testing by modules inserting, then exit from kernel
	cmd /sbin/modprobe tcrypt sec=$period mode=$i
done

# to silence the "expected" failure explicitly:
#    modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
exit 0
