#!/bin/sh
# - runtime

## The program thrulay is used to measure the capacity, delay,
## and other performance metrics of a network by sending a
## bulk TCP or UDP stream over it.

export PATH=$BENCHMARK_ROOT/thrulay/sbin:$BENCHMARK_ROOT/thrulay/bin:$PATH

[ -n "$runtime" ] || runtime=300

[ -n "$direct_server_ips" ] && server=$direct_server_ips
[ -z "$server" ] && server=127.0.0.1
server=${server%% *}

export LD_LIBRARY_PATH=/lkp/benchmarks/thrulay/lib:$LD_LIBRARY_PATH
log_cmd thrulay -t $runtime $server
