#!/bin/sh
# - runtime

export PATH=$BENCHMARK_ROOT/thrulay/sbin:$BENCHMARK_ROOT/thrulay/bin:$PATH

[ -n "$runtime" ] || runtime=300

[ -z "$server" ] && server=127.0.0.1
server=${server%% *}

cmd thrulay -t $runtime $server
