#!/bin/sh
# - runtime
# - test
# - nr_task

## UnixBench is the original BYTE UNIX benchmark suite. The purpose
## of UnixBench is to provide a basic indicator of the performance
## of a Unix-like system; hence, multiple tests are used to test
## various aspects of the system's performance.

cd $BENCHMARK_ROOT/unixbench || exit

export LANG=C

[ -n "$runtime" ] || runtime=300

# Each iteration in UnixBench is about 10 seconds
iteration=$(( runtime / 10 ))

[ -n "$nr_task" ] && other_params="-c $nr_task"

log_cmd ./Run $test $other_params -i $iteration || exit

copy-results $BENCHMARK_ROOT/unixbench/results/*
