#!/bin/bash
# - test

cd $BENCHMARK_ROOT/unixbench || exit

export LANG=C

cmd ./Run $test

chmod g+w $BENCHMARK_ROOT/unixbench/results/*
chown lkp.lkp $BENCHMARK_ROOT/unixbench/results/*
cp -a $BENCHMARK_ROOT/unixbench/results/* $RESULT_ROOT/
