#!/bin/sh
# - runtime
# - test
# - nr_task

cd $BENCHMARK_ROOT/will-it-scale || exit

setup_params()
{
	iterations=$((3 + nr_node))
	duration=$(( runtime / iterations / 2 - WARMUP_ITERATIONS ))
	[ "$duration" -lt 5  ] && duration=5
}

[ -n "$runtime" ] || runtime=300
WARMUP_ITERATIONS=5 # defined in will-it-scale/main.c

if [ -n "$nr_task" ]; then
	# one shot run
	duration=$(( runtime - WARMUP_ITERATIONS ))
	threads_to_iterate=$nr_task
else
	. $LKP_SRC/lib/sysinfo.sh
	setup_threads_to_iterate
	setup_params
fi

cmd ./runtest.py $test $duration $threads_to_iterate
