#!/bin/sh
# - test

## Regression test suite for xfs and other filesystems.

. $LKP_SRC/lib/job.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/reproduce-log.sh

[ "$nr_partitions" -lt 2 ] && die "$nr_partitions -lt 2"
cd $BENCHMARK_ROOT/xfstests || die "fail to cd $BENCHMARK_ROOT/xfstests"

check_add_user()
{
	[ "x$1" != "x" ] || return
	grep -q -w "$1" /etc/passwd && return
	useradd "$1" || echo "$(basename $0): useradd $1 failed" 1>&2
}

set_env()
{
	# "fsgqa" user is required in some of xfstests, thus check if such user
	# has already been added. If not, add "fsgqa" user.
	check_add_user "fsgqa"
	check_add_user "123456-fsgqa"

	umount $mount_points

	# clear filesystem in partition
	for dev in ${partitions#* }
	do
		dd if=/dev/zero bs=512 count=512 of=$dev
	done

	log_eval export TEST_DIR=${mount_points%% *}
	log_eval export TEST_DEV=${partitions%% *}

	# f2fs needs this to prevent mount failure
	log_eval export FSTYP=$fs
	log_eval export SCRATCH_MNT=/fs/scratch

	log_cmd mkdir $SCRATCH_MNT -p

	if [ "$fs" = btrfs ] && [ "$nr_partitions" -ge 4 ]; then
		log_eval export SCRATCH_DEV_POOL=\"${partitions#* }\"
	else
		log_eval export SCRATCH_DEV=${partitions##* }
	fi

	[ "$fs" = f2fs ] && log_eval export MKFS_OPTIONS="-f"

	## We could use the "pack-deps" job to generate the relevant dependency package with cgz format,
	## but sometimes the dependency package have a different layout with the original package.
	## For examle:
	## 1)the command "btrfs" under directory /sbin  in original rootfs.
	## 2)the command "btrfs" under directory /bin  in dependency packages.
	## this will result in the newer btrfs command can't override the original btrfs command,
	## moreover, /bin behind with /sbin directory in the default "PATH" environment.
	## so we need to adjust the "PATH" search order.
	export PATH="/bin/":$PATH

	if [ "$fs" = xfs ] && [ "$nr_partitions" -ge 3 ]; then
		SCRATCH_LOGDEV=${partitions#* }
		SCRATCH_LOGDEV=${SCRATCH_LOGDEV%% *}
		log_eval export SCRATCH_LOGDEV="$SCRATCH_LOGDEV"
	fi

	[ "${test%%-*}" = "xfs" ] && {
		log_eval export SCRATCH_XFS_LIST_METADATA_FIELDS=u3.sfdir3.hdr.parent.i4
		log_eval export SCRATCH_XFS_LIST_FUZZ_VERBS=random
	}

	[ "$test" = "xfs-no_bug_assert" ] && {
		[ -f /sys/fs/xfs/debug/bug_on_assert ] && echo 0 > /sys/fs/xfs/debug/bug_on_assert
	}

	[ "$test" = "xfs-275" ] && {
		log_eval export USE_EXTERNAL=yes
		# create a 100M partition for log, avoid
		# log size 67108864 blocks too large, maximum size is 1048576 blocks
		printf "n\np\n1\n\n+100M\nw\n" | fdisk $SCRATCH_LOGDEV
		log_eval export SCRATCH_LOGDEV="$SCRATCH_LOGDEV"1
	}

	[ "$test" = "xfs-437" ] && {
		echo "LC_ALL=en_US.UTF-8" >> /etc/environment
		echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
		echo "LANG=en_US.UTF-8" > /etc/locale.conf
		locale-gen en_US.UTF-8
		log_eval export WORKAREA="$BENCHMARK_ROOT/xfstests/xfsprogs-dev"
	}

	[ "$test" = "xfs-external" ] && {
		log_eval export USE_EXTERNAL="yes"
		log_eval export SCRATCH_RTDEV="$SCRATCH_LOGDEV"
		log_eval export MKFS_OPTIONS="-mreflink=1"
		log_eval unset SCRATCH_LOGDEV
	}
	[ "$test" = "xfs-reflink_rmapbt" ] && log_eval export MKFS_OPTIONS="\"-mreflink=1 -mrmapbt=1\""
	[ "$test" = "xfs-reflink" ] && log_eval export MKFS_OPTIONS="-mreflink=1"
	[ "$test" = "xfs-rmapbt" ] && log_eval export MKFS_OPTIONS="-mrmapbt=1"
	[ "$test" = "xfs-244" ] && log_eval export MKFS_OPTIONS="-mcrc=0"
	[ "$test" = "xfs-132" ] && (mkfs.xfs -f -mreflink=1 $TEST_DEV || die "mkfs.xfs test_dev failed")

	if [ "$fs" = xfs ] && [ "${test%?}" = "generic-group" ]; then
		mkfs.xfs -f -mreflink=1 $TEST_DEV || die "mkfs.xfs test_dev failed"
		log_eval export MKFS_OPTIONS="-mreflink=1"
	fi

	[ "$test" = "generic-387" ] && {
		printf "n\np\n1\n\n+1G\nw\n" | fdisk $SCRATCH_DEV
		log_eval export SCRATCH_DEV="$SCRATCH_DEV"1
	}

	# need at least 3 partitions for TEST_DEV, SCRATCH_DEV and LOGWRITES_DEV
	if [ "$test" = "generic-logwrites" ] && [ "$nr_partitions" -ge 3 ]; then
		LOGWRITES_DEV=${partitions#* }
		LOGWRITES_DEV=${LOGWRITES_DEV%% *}
		log_eval export LOGWRITES_DEV="$LOGWRITES_DEV"
		[ "$fs" = "xfs" ] && log_eval export MKFS_OPTIONS="-mreflink=1"
	fi

	if [ "$test" = "generic-470" ] && [ "$nr_partitions" -ge 3 ]; then
		LOGWRITES_DEV=${partitions#* }
		LOGWRITES_DEV=${LOGWRITES_DEV%% *}
		log_eval export LOGWRITES_DEV="$LOGWRITES_DEV"
		[ "$fs" = "xfs" ] && unset MKFS_OPTIONS
	fi
}

ignore_and_do_tests()
{
	local all_tests_cmd="$1"

	[ "$2" ] && cat $2 2>/dev/null | sort | uniq > merged_ignored_files

	[ -s "merged_ignored_files" ] && {
		ignored_tests_cmd=${all_tests_cmd}" | grep -F -f merged_ignored_files"
		all_tests_cmd=${all_tests_cmd}" | grep -v -F -f merged_ignored_files"

		log_eval $ignored_tests_cmd
		for ignored_test in $(eval $ignored_tests_cmd)
		do
			echo "ignored by lkp: $ignored_test"
		done
	}
	log_eval $all_tests_cmd
	log_cmd ./check $(eval $all_tests_cmd)
}

run_test()
{
	## Currently, we support the following several format's test item.
	## Not-run, out-mismatch files are hard to maintain and do not use in the test, so remove them.
	## With "generic" testcase as an example:
	## - generic-all
	## - generic-127
	## - generic-quick/mid/slow1/slow2
	## - generic-new

	local test_dir="$LKP_SRC/pack/xfstests-addon/tests"

	# the ignore file like xfs-ignore, but $test like xfs-group1, so need to get its prefix.
	local test_ignore="$test_dir/${test%-*}-ignore"
	# /$BENCHMARK_ROOT/xfstests/${test%-*}-ignore is built from upstream blacklist
	test_ignore="$test_ignore /$BENCHMARK_ROOT/xfstests/${test%-*}-ignore"

	if [ "${test#*-}" = "all" ]; then
		all_tests_cmd="cd tests && ls ${test%-*}/[0-9][0-9][0-9]"
		ignore_and_do_tests "$all_tests_cmd"
	elif [ "${test#*-}" = "new" ]; then
		all_tests_cmd="cd tests && sed \"s:^:${test%-*}/:\" $test"
		ignore_and_do_tests "$all_tests_cmd"
	elif [ "${test%[a-z4]-[0-9][0-9][0-9]}" != "$test" ]; then
		all_tests_cmd="echo ${test%-*}/${test#*-}"
		ignore_and_do_tests "$all_tests_cmd"
	elif [ "${test#*-}" != "$test" ]; then
		generic_fs_ignore="$test_dir/${test%-*}-$fs-ignore /$BENCHMARK_ROOT/xfstests/generic-$fs-ignore"
		all_tests_cmd="sed \"s:^:${test%-*}/:\" $test_dir/$test"
		ignore_and_do_tests "$all_tests_cmd" "$test_ignore $generic_fs_ignore"
	else
		# Now rename $test-broken to $test-ignore wihch is easier to understand.
		# Use $test_ignore and $BENCHMARK_ROOT/$casename/ignore to skip tests which are hard to enable.
		pack_ignore="/$BENCHMARK_ROOT/xfstests/ignore"
		all_tests_cmd="cd tests && ls $test/[0-9][0-9][0-9]"
		ignore_and_do_tests "$all_tests_cmd" "$test_ignore $pack_ignore"
	fi
}

export LC_ALL=C
export LANG=C
read_env_vars
set_env
run_test
exit_value=$?

upload_files -t results $BENCHMARK_ROOT/xfstests/results/*
exit $exit_value
