#!/bin/sh

. $LKP_SRC/lib/job.sh
read_env_vars	# for $partitions

for dev in $partitions; do
	# skip nfs dev
	[ "${dev#*:/}" != "$dev" ] && continue
	# skip pmem dev
	[ "${dev#*pmem}" != "$dev" ] && continue

	[ "${dev#/dev/md}" != "$dev" ]	||
	[ "${dev#/dev/ram}" != "$dev" ]	||
	[ "${dev#/dev/nvme}" != "$dev" ] && dev=$(echo "$dev" | sed 's/p.*//') ||
	dev=$(echo "$dev" | tr -d '0-9')
	bdi=$(ls -l $dev | sed 's/,[[:space:]]*/:/' | awk '{print $5}')
	echo "'$bdi': ${dev#/dev/}"
done
