#!/bin/sh

. $LKP_SRC/lib/reproduce-log.sh

cassandra_server=$BENCHMARK_ROOT/cassandra/bin/cassandra

# log command
log_echo $cassandra_server -f -R

# start cassandra server
exec $cassandra_server -f -R
