#!/bin/sh
# - mongodb_cpu_node_bind
# - mongodb_mem_node_bind
# - nr_processes

. "$LKP_SRC/lib/reproduce-log.sh"
. "$LKP_SRC/lib/numactl.sh"

bg_pids=""
mongodb_server="$BENCHMARK_ROOT/mongodb/bin/mongod"

if [ -n "$mount_points" ]; then
	MONGODB_DIR="${mount_points%% *}"
else
	echo "Can not get the mount points, exit!" 1>&2
	exit 1
fi

parse_numa_node_binding "$mongodb_cpu_node_bind" "$mongodb_mem_node_bind"

# start mongodb server
for i in $(seq 1 "$nr_processes")
do
	port=$((27016+i))
	numa_bind=$(numa_node_binding "$i")
	log_eval "$numa_bind $mongodb_server --port $port --dbpath=${MONGODB_DIR}/mongodb/dbdir_$i/ --config ${TMP_RESULT_ROOT}/mongod.conf.$i &"
	bg_pids="$bg_pids $!"
done

cat > "$TMP_RESULT_ROOT/post-run.mongodb" <<EOF
/bin/kill -15 $bg_pids
EOF
