#!/bin/sh
# - tbox_group
# - nr_container
# - queues

# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

multi_docker()
{
	export CCI_SRC=${CCI_SRC:-"/c/compass-ci"}
	local hostname=$tbox_group.$HOSTNAME
	$CCI_SRC/providers/multi-docker -n $hostname -c $nr_container -q $queues
}

multi_docker
