#!/bin/sh
# - tbox_group
# - nr_vm
# - queues

# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

: ${queues:="$tbox_group.$HOSTNAME,$tbox_group.$(arch)"}

multi_qemu()
{
	export CCI_SRC=${CCI_SRC:-"/c/compass-ci"}
	local hostname=$tbox_group.$HOSTNAME

	mkdir -p /srv/$suite && cd /srv/$suite
	[ -d "mount_point" ] && cd "$mount_point"
	$CCI_SRC/providers/multi-qemu -n "$hostname" -c "$nr_vm" -q "$queues"
}

multi_qemu
