#!/bin/sh
# - nr_processes
# - cpu_node_bind
. $LKP_SRC/lib/reproduce-log.sh
bg_pids=""
redis_server=$BENCHMARK_ROOT/redis/bin/redis-server
# start redis server
for i in $(seq 1 "${nr_processes}")
do
	port=$((6379+$i))
	if [ -n "$cpu_node_bind" ]; then
		if [ "$cpu_node_bind" = "even" ]; then
			bind=$(($i%nr_node))
		else
			bind=$cpu_node_bind
		fi
		numa_bind="numactl --cpunodebind=$bind --"
	fi
	log_eval "$numa_bind $redis_server --port $port &"
	bg_pids="$bg_pids $!"
done

cat > $TMP_RESULT_ROOT/post-run.redis <<EOF
/bin/kill -9 $bg_pids
EOF
