#!/usr/bin/env ruby

LKP_SRC = ENV["LKP_SRC"] || File.dirname(File.dirname File.realpath $PROGRAM_NAME)
ENV["LKP_SRC"] ||= LKP_SRC

require "#{LKP_SRC}/lib/job.rb"

def run_program(program)
	printf "run: %s\n", $programs[program]
	system $job_vars, [ $programs[program], program ]
end

def get_yaml_vars(file, job_vars)
	env_yaml = `#{LKP_SRC}/bin/job-env #{file}`
	begin
		env = YAML.load env_yaml
	rescue Psych::SyntaxError => e
		STDERR.puts e.message
		STDERR.puts env_yaml
	end
	env.each { |key, val| job_vars[key.gsub(/[^a-zA-Z0-9_]/, '_')] = val.to_s }
end

def get_job_vars(job, jobfile)
	testbox = job['testbox'] || ENV["HOSTNAME"] || `hostname`.chomp
	hostcfg = "#{LKP_SRC}/hosts/#{tbox_group(testbox)}"

	job_vars = { 'testbox' => testbox }
	get_yaml_vars hostcfg, job_vars
	get_yaml_vars jobfile, job_vars
	job_vars['job_file'] = jobfile
	job_vars['path_params'] = `#{LKP_SRC}/bin/job-path #{jobfile}`.chomp

	YAML.dump job_vars if ENV['LKP_VERBOSE']
	return job_vars
end

jobfile = ARGV[0]
job = Job.new
job.load(jobfile)
$job_vars = get_job_vars job, jobfile

if $PROGRAM_NAME =~ /job-vars/
	$job_vars.each { |k, v| puts "#{k}=#{v.inspect}" }
	exit
end

job.each_program("{filters}/**/*") { |program, env|
	run_program program
	break unless File.exist? jobfile
}
