#!/usr/bin/env ruby

TMP = ENV['TMP'] || '/tmp'
LKP_SRC = ENV["LKP_SRC"] || File.dirname(File.dirname File.realpath $PROGRAM_NAME)

require "#{LKP_SRC}/lib/job2sh.rb"
require "#{LKP_SRC}/lib/job.rb"
require 'optparse'
require 'ostruct'
require 'yaml'

$opt_file = STDOUT

opts = OptionParser.new do |opts|
	opts.banner = "Usage: #{$PROGRAM_NAME} [options] job.yaml"

	opts.separator ''
	opts.separator 'options:'

	opts.on('-o FILE', '--output FILE', 'save shell script to FILE (default: stdout)') do |file|
		$opt_file = File.open(file, mode='w', perm=0755)
	end

	opts.on_tail('-h', '--help', 'Show this message') do
		puts opts
		exit
	end

end

if ARGV == []
	argv = ['-h']
else
	argv = ARGV
end
opts.parse!(argv)

job = YAML.load_file(ARGV[0])
job2sh(job, $opt_file)
