#!/bin/bash

[[ $LKP_SRC ]] || export LKP_SRC="$(dirname $(dirname $(readlink -e -v $0)))"

PACK_NAME=$1
BM_NAME=${PACK_NAME%-*}
DISTRO=${PACK_NAME##*-}

umask 002

. $LKP_SRC/distro/${DISTRO}

rootfs=debian-x86_64.cgz
pack_to=/osimage/deps/$rootfs
mkdir -p $pack_to

check_shared_package "$BM_NAME" && exit

work_dir=$(mktemp -d)
cd $work_dir

download $(get_dependency_packages $DISTRO $BM_NAME) || exit
install
pack
