#!/bin/bash

[[ $LKP_SRC ]] || export LKP_SRC="$(dirname $(dirname $(readlink -e -v $0)))"

rootfs=$1
BM_NAME=$2

[[ $BM_NAME ]] || {
	echo Usage: $0 rootfs BM_NAME
	exit 1
}

umask 002

DISTRO=${rootfs%%-*}
. $LKP_SRC/distro/$DISTRO

pack_to=/osimage/deps/$rootfs
mkdir -p $pack_to

check_shared_package "$BM_NAME" && exit

work_dir=$(mktemp -d /tmp/pack-deps-$BM_NAME-XXXXXXXXX)
cd $work_dir

download $(get_dependency_packages $DISTRO $BM_NAME) || exit
install
pack
