#! /usr/bin/env ruby

# frozen_string_literal: true

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))
CCI_LAB ||= ENV['CCI_LAB'] || 'sparrow'

require "#{LKP_SRC}/lib/job2sh"
require "#{LKP_SRC}/lib/scheduler_client"
require 'optparse'
require 'yaml'

opt_set_key_value = {}

options = OptionParser.new do |opts|
  opts.banner = 'Usage: submit-job [options] jobs...'

  opts.separator ''
  opts.separator 'options:'

  opts.on("-s 'KEY: VALUE'", "--set 'KEY: VALUE'", 'add YAML hash to job') do |key_value|
    opt_set_key_value.merge! YAML.load key_value
  end
end

options.parse!(ARGV)

ARGV.delete_if do |arg|
  if arg.index '='
    opt_set_key_value.merge! YAML.load arg.sub(/=/, ': ')
    true
  else
    false
  end
end

if ARGV.size.zero?
  puts(options)
  exit
end

lab_path = "#{LKP_SRC}/labs/#{CCI_LAB}.yaml"

ARGV.each do |jobfile|
  jobs = Job2sh.new
  jobs.load(jobfile, true) || next
  jobs.load_one_defaults(lab_path, jobs.to_hash)
  jobs.overrides = opt_set_key_value
  jobs.each_jobs do |job|
    # get job shell function
    sh_run_job = job.sh_run_job
    sh_extract_stats = job.sh_extract_stats
    sh_hash = {"job2sh" => {"run_job" => sh_run_job, "extract_stats" => sh_extract_stats}}
    
    # merge job info
    job_hash = job.to_hash
    job_hash = job_hash.merge(sh_hash)

    # init scheduler client 
    host = job_hash['SCHED_IP'] || '127.0.0.1'
    port = job_hash['SCHED_PORT'] || 3000
    scheduler_client = SchedulerClient.new(host, port)
    
    # submit job
    job_json = job_hash.to_json
    job_id = scheduler_client.submit_job(job_json)
    puts("succeeded submitting #{jobfile}, got job id = #{job_id}")
  end
end
