#!/bin/sh

for dev in $partitions; do
	# skip nfs dev
	[ "${dev#*:/}" != "$dev" ] && continue

	[ "${dev#/dev/md}" != "$dev" ]	||
	[ "${dev#/dev/ram}" != "$dev" ]	|| dev=$(echo "$dev" | tr -d '[0-9]')
	bdi=$(ls -l $dev | sed 's/,[[:space:]]*/:/' | awk '{print $5}')
	echo "'$bdi': ${dev#/dev/}"
done
