#!/bin/sh

. $LKP_SRC/lib/env.sh

has_cmd ethtool || exit 0

IFACE=eth0 # FIXME

take_snapshot()
{
	echo time: $(date +%s.%N)
	ethtool -S $IFACE
}

take_snapshot

. $LKP_SRC/lib/wait.sh
setup_wait

wait_post_test

take_snapshot
