#!/bin/sh
# - delay
# - duration
# - buffer_size_kb
# - ftrace_options
# - functions
# - graph_functions
# - trace_clock
# - ftrace_cpulist

. $LKP_SRC/lib/ftrace.sh
setup_wait

current_tracer=function_graph
ftrace_filters=$functions
ftrace_options="nofuncgraph-overhead nofuncgraph-cpu funcgraph-proc funcgraph-duration funcgraph-tail"
ftrace_set_params

ftrace_run
