#!/bin/sh
# - interval

. $LKP_SRC/lib/kmemleak.sh
. $LKP_SRC/lib/wait.sh

kmemleak_is_enabled || return

setup_wait

: ${interval:=10}

while :
do
	echo scan >/sys/kernel/debug/kmemleak
	cat /sys/kernel/debug/kmemleak
	echo clear >/sys/kernel/debug/kmemleak
	wait_timeout $interval
done
