#!/bin/sh

# reference code: linux/kernel/latencytop.c

[ -n "$disable_latency_stats" ] && exit 0

[ -f "/proc/latency_stats" ] || exit 0

snapshot()
{
	echo time: $(date +%s.%N)
	cat /proc/latency_stats
}

echo 0 > /proc/latency_stats
echo -n 1 > /proc/sys/kernel/latencytop

. $LKP_SRC/lib/wait.sh
setup_wait

wait_post_test
snapshot
echo -n 0 > /proc/sys/kernel/latencytop
