#!/bin/sh

. $LKP_SRC/lib/wait.sh
setup_wait

# dont OOM kill me
# dont change me, "echo -1000" won't work well with some stdbuf,
# and maybe appear like this error "echo: write error: Invalid argument".
cat > /proc/$$/oom_score_adj <<EOF
-1000
EOF

while :
do
	wait_timeout 11

	[ -f "$TMP/job-finished" ] && exit

	check_oom && break
done

touch $RESULT_ROOT/OOM
echo "Out of memory, stop tests programs"
kill_tests
