#!/bin/sh
# - events
# - revents
# - time
# - command

# perf may consume lots of fd
ulimit -n 102400

if [ -n "$revents" ]; then
	events="$revents"
else
	[ -n "$events" ] || events='hardware cache software'
	events=$(perf-events $events)
	[ -n "$events" ] || exit
fi

opt_events="-e $(echo $events | sed 's/ / -e /g')"

[ -n "$command" ] || {
	. $LKP_SRC/lib/wait.sh
	setup_wait

	if [ -n "$time" ]; then
		command="$WAIT_POST_TEST_CMD --timeout $time"
	else
		command="$WAIT_POST_TEST_CMD"
	fi
}

exec perf stat -a -I 1000 -x' ' $opt_events --log-fd 1 -- $command
