#!/bin/sh
# - interval

file=$(basename $0)
file=${file#proc-}

[ -f /proc/$file ] || exit

if [ -z "$interval" ]; then
	case $file in
		sched_debug)	interval=60 ;;
		stat)		interval=10 ;;
		zoneinfo)	interval=10 ;;
		*)		interval=1  ;;
	esac
fi

. $LKP_SRC/lib/wait.sh
setup_wait

if [ $file = 'vmstat' ]; then
	cat()
	{
		awk '!x[$1]++' "$@"
	}
fi

while :
do
	echo time: $(date +%s.%N)
	cat /proc/$file
	wait_timeout $interval
done
