#!/bin/sh

. $LKP_SRC/lib/wait.sh
setup_wait

# dont OOM kill me
echo -1000 > /proc/$$/oom_score_adj

while :
do
	wait_timeout 11

	[ -f "$TMP/job-finished" ] && exit

	grep -s -q -F -e 'Out of memory' -e 'invoked oom-killer: gfp_mask=0x' $RESULT_ROOT/kmsg && {
		touch $TMP/OOM
		touch $RESULT_ROOT/OOM
		echo "$(date)  Out of memory, stop tests programs"
		df -t tmpfs
		kill_tests
		exit
	}
done
