#!/bin/sh

[ -n "$max_uptime" ] || max_uptime=$((5 * 3600))
max_uptime=${max_uptime%%.*}

. $LKP_SRC/lib/wait.sh
setup_wait

wait_post_test --timeout $max_uptime && {
	exit 0
}

touch $TMP/soft_timeout

# try to unblock the main shell, which will copy files to
# $RESULT_ROOT, which helps debug the hang reason
kill $(cat $TMP/pid-* /dev/null) 2>/dev/null
sleep 3
kill -9 $(cat $TMP/pid-* /dev/null) 2>/dev/null

# reboot it the hard way, if the main shell failed to reboot
sleep 3m && {
	echo w > /proc/sysrq-trigger
	echo s > /proc/sysrq-trigger
	sleep 10
	echo b > /proc/sysrq-trigger
}
