#!/bin/sh
### BEGIN INIT INFO
# Provides:          lkp-bootstrap
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: LKP bootstrap
# Description:       LKP bootstrap
### END INIT INFO

mkdir /dev/shm/lkp-bootstrap-once 2>/dev/null || exit 0

read_kernel_cmdline_vars()
{
	[ -f /proc/cmdline ] || return 1

	for i in $(cat /proc/cmdline)
	do
		[ "${i#user=}" != "$i" ] && export $i
		[ "${i#job=}" != "$i" ] && export $i
		[ "${i#ip=}" != "$i" ] && export $i
	done
	return 0
}

read_kernel_cmdline_vars
[ -n "$job" ] || job=$(echo /lkp/scheduled/*/*.yaml) # in case CONFIG_PROC_FS is not set
[ -e "$job" ] || {
	echo $job does not exist, quit from LKP
	exit 0 # to work with non-LKP boots
}
. ${job%.yaml}.sh
export_top_env

: ${user:=lkp}
export LKP_SRC=/lkp/$user/src

$LKP_DEBUG_PREFIX $LKP_SRC/bin/lkp-setup-rootfs
