#!/bin/bash

WEB_URL="http://nchc.dl.sourceforge.net/project/aimbench/aim-suite7/Initial%20release/s7110.tar.Z"
source_dir="aim7"

build()
{
	patch_source
	make <<-END


1
gcc
-O2


n
END
	make
}

install()
{
	find . -maxdepth 1 -type f -executable ! -name ".*" \
		-exec cp -af {} $BM_ROOT \;
	cp fakeh.tar $BM_ROOT
	mkdir -p "$BM_ROOT/workfiles"
	cp -af workfile.* $BM_ROOT/workfiles
}
