#!/bin/bash

VERSION=1.1
WEB_URL="http://download.pureftpd.org/pub/blogbench/blogbench-${VERSION}.tar.gz"

build()
{
    cp /usr/share/misc/config.{guess,sub} .
    ./configure
    make
}

install()
{
	cp -af src/blogbench ${BM_ROOT}
}
