#!/bin/bash

git_clone_update()
{
	local url=$1
	local dir=$2
	[[ $dir ]] || dir=$(basename $url .git)

	if [[ -d $dir/.git ]]; then
		(
			cd $dir
			git remote update origin
			git checkout origin/master
		)
	else
		rm -fr "$dir"
		git clone $url $dir
	fi
}

pre_download()
{
	:
}

download()
{
	pre_download
	[[ $WEB_URL ]] && wget --no-clobber $WEB_URL
	[[ $source_package ]] || source_package=$(basename $WEB_URL)
	[[ $source_dir     ]] || source_dir=${source_package%%.tar.*}
	[[ -d $source_dir ]] ||
	tar xf "$source_package"
}

patch_source()
{
	PATCH=$LKP_SRC/pack/${BM_NAME}.patch
	[[ -f $PATCH ]] || return 0
	patch -p1 < $PATCH
}

build()
{
	cd $source_dir
	patch_source
	[[ -x "./configure" ]] && ./configure $CONFIGURE_FLAGS
	make
}

install()
{
	make install-exec
}

pack_deb()
{
	local deb_name="${BM_NAME//_/-}-LKP"
	rm -fr "/tmp/$deb_name"
	mkdir -p /tmp/$deb_name/$BM_ROOT
	cp -af $BM_ROOT /tmp/$deb_name/lkp/benchmarks
	mkdir -p /tmp/$deb_name/DEBIAN
	cat > /tmp/$deb_name/DEBIAN/control <<-EOF
	Package: $deb_name
	Version: $(date +%F)
	Architecture: all
	Maintainer: LKP
	Description: LKP dependent packages
	EOF

	cd /tmp
	dpkg-deb --build $deb_name
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		find /lkp/benchmarks/$BM_NAME
	} |
	cpio -o -H newc | gzip -n -9 > /tmp/${BM_NAME}.cgz
	[[ $arch ]] && mv "/tmp/${BM_NAME}.cgz" "/tmp/${BM_NAME}-${arch}.cgz"
}

post_cleanup()
{
	:
}

cleanup()
{
	[[ $source_package ]] && rm -f  "/tmp/${source_package}"
	[[ $source_dir     ]] && rm -fr "/tmp/${source_dir}"
	post_cleanup
}
