#!/bin/bash

download()
{
	# git_clone_update https://github.com/rminnich/ftq.git
	# Use Ying's git temporary until the fixes are merged by upstream
	git_clone_update https://github.com/hying-caritas/ftq.git
}

build()
{
	make
}

install()
{
	for f in ftq_*; do
		[ -x $f ] && cp -af $f $BM_ROOT
	done
}
