#!/bin/bash

download()
{
	git_clone_update https://github.com/bcopeland/wmediumd.git || return
	git_clone_update git://w1.fi/srv/git/hostap.git
}

build()
{
	cd ../wmediumd || return
	make || return
	# binary will be installed into /usr/bin/wmediumd
	make install || return
	cd -

	# support WPA-EAP-SUITE-B-192, example-wpa_supplicant.config and example-hostapd.config contains support options for build.
	# hostapd_config_parse_key_mgmt() in hostapd/config_file.c will check "CONFIG_SUITEB192".
	# if not set "CONFIG_SUITEB192=y", suite_b_192 can not be added into key_mnt.

	# if example-wpa_supplicant.config and example-hostapd.config not exist, it means hostap(git://w1.fi/srv/git/hostap.git)
	# remove the files, we need to check the option in the new configuration files
	local wpa_supplicant_config="./tests/hwsim/example-wpa_supplicant.config"
	local hostapd_config="./tests/hwsim/example-hostapd.config"

	if [[ -f $wpa_supplicant_config ]]; then
		grep -q -w "CONFIG_SUITEB192=y" $wpa_supplicant_config || echo "CONFIG_SUITEB192=y" >> $wpa_supplicant_config
	else
		echo "Warning: $wpa_supplicant_config not exist, failed to set CONFIG_SUITEB192=y"
	fi
	if [[ -f $hostapd_config ]]; then
		grep -q -w "CONFIG_SUITEB192=y" $hostapd_config || echo "CONFIG_SUITEB192=y" >> $hostapd_config
	else
		echo "Warning: $hostapd_config not exist, failed to set CONFIG_SUITEB192=y"
	fi
}

build_hwsim_param_long()
{
	# try to find out the case requiring params long
	# root@debian9:/home/lizhijian/chroot/lkp/benchmarks/hwsim/tests/hwsim# git grep -B 2 -w 'if not params\['\'long\']
	# test_ap_ciphers.py-def test_ap_cipher_tkip_countermeasures_sta2(dev, apdev, params):
	# test_ap_ciphers.py-    """WPA-PSK/TKIP countermeasures (detected by two STAs) [long]"""
	# test_ap_ciphers.py:    if not params['long']:

	cd $source_dir/tests/hwsim
	git grep -B 2 -w 'if not params\['\'long\'] | grep '.*\.py\-def' | awk -F 'def ' '{print $2}' | awk -F'(' '{print $1}' | sed s/test_//g > require_long_param
}

build_hwsim_require_mcc()
{
    cd $source_dir/tests/hwsim
    git grep -E -e 'def test.*mcc' | awk -F 'test_' '{print $3}'| awk -F '(' '{print $1}' > require_mcc
}

build_ignored_by_lkp()
{
	local ignored_by_lkp="ignored_by_lkp"
	cd $source_dir/tests/hwsim

	# try to find out the case requiring under vm
	# root@debian9:/lkp/benchmarks/hwsim/tests/hwsim# git grep -B 2 -w 'require_under_vm'
	# test_ap_dynamic.py-import hwsim_utils
	# test_ap_dynamic.py-import hostapd
	# test_ap_dynamic.py:from utils import alloc_fail, require_under_vm, get_phy
	# --
	# test_ap_dynamic.py-def test_ap_iapp(dev, apdev):
	# test_ap_dynamic.py-    """IAPP and multiple BSSes"""
	# test_ap_dynamic.py:    require_under_vm()
	echo "# ignore _require_under_vm_" >> $ignored_by_lkp
	git grep -B 2 -w 'require_under_vm' | grep '\-def ' | grep -v _test | awk -F' test_' '{print $2}' | awk -F'(' '{print $1}' >> $ignored_by_lkp
	special_case=$(git grep -B 2 -w 'require_under_vm' | grep '\-def ' | grep _test | awk -F'-def ' '{print $2}' | awk -F'(' '{print $1}')
	for s in $special_case
	do
		git grep -B 2 -w "$s" | grep '\-def ' | grep -v _test | awk -F' test_' '{print $2}' | awk -F'(' '{print $1}' >> $ignored_by_lkp
	done

	echo "# ignore _hostap_not_support_" >> $ignored_by_lkp
	echo "eap_fast_tlv_nak_oom" >> $ignored_by_lkp
	echo "fils_sk_hlp_oom" >> $ignored_by_lkp
	echo "gas_rand_ta" >> $ignored_by_lkp
	echo "proxyarp_open_ipv6" >> $ignored_by_lkp
	echo "proxyarp_open_ebtables_ipv6" >> $ignored_by_lkp

	echo "# ignore _hostap_not_test_" >> $ignored_by_lkp
	echo "wmediumd_path_rann" >> $ignored_by_lkp
	echo "ap_beacon_rate_ht" >> $ignored_by_lkp
	echo "ap_beacon_rate_ht2" >> $ignored_by_lkp
	echo "ap_beacon_rate_legacy" >> $ignored_by_lkp
	echo "ap_beacon_rate_legacy2" >> $ignored_by_lkp
	echo "ap_beacon_rate_vht" >> $ignored_by_lkp
	echo "ap_cipher_tkip_countermeasures_sta2" >> $ignored_by_lkp
	echo "ap_wpa2_eap_tls_intermediate_ca_ocsp_multi" >> $ignored_by_lkp
	echo "ap_wpa2_eap_tls_intermediate_ca_ocsp_multi_missing_resp" >> $ignored_by_lkp
	echo "ap_wpa2_eap_tls_ocsp_multi" >> $ignored_by_lkp
	echo "ap_wpa2_eap_tls_ocsp_multi_revoked" >> $ignored_by_lkp
	echo "dbus_tdls_channel_switch" >> $ignored_by_lkp
	echo "dpp_config_dpp_gen_secp521r1_secp521r1" >> $ignored_by_lkp
	echo "dpp_config_dpp_override_secp384r1" >> $ignored_by_lkp
	echo "dpp_config_fragmentation" >> $ignored_by_lkp
	echo "dpp_pkex" >> $ignored_by_lkp
	echo "dpp_pkex_bp256" >> $ignored_by_lkp
	echo "dpp_qr_code_auth_responder_configurator" >> $ignored_by_lkp
	echo "dpp_qr_code_curve_secp384r1" >> $ignored_by_lkp
	echo "dpp_gas_timeout" >> $ignored_by_lkp
	echo "dpp_hostapd_configurator" >> $ignored_by_lkp
	git grep -E -e 'def test.*sigma_dut' | awk -F 'test_' '{print $3}'| awk -F '(' '{print $1}' >> $ignored_by_lkp

	echo "# ignore _hostap_not_support_lifetime_in_memory_" >> $ignored_by_lkp
	git grep -E -e 'def test.*lifetime_in_memory' | awk -F 'test_' '{print $3}'| awk -F '(' '{print $1}' >> $ignored_by_lkp

	echo "# ignore _mac80211_hwsim_not_support_" >> $ignored_by_lkp
	echo "tdls_chan_switch" >> $ignored_by_lkp
	echo "rrm_link_measurement" >> $ignored_by_lkp
	echo "rrm_link_measurement_oom" >> $ignored_by_lkp	

	echo "# ignore _result_is_not_stable_" >> $ignored_by_lkp
	echo "autogo_join_auto_go_neg_after_seeing_go" >> $ignored_by_lkp
	echo "ap_vht160" >> $ignored_by_lkp
	echo "ap_wpa2_eap_eke_server_oom" >> $ignored_by_lkp
	echo "ap_wpa2_eap_eke_serverid_nai" >> $ignored_by_lkp
	echo "ap_wpa2_eap_in_bridge" >> $ignored_by_lkp
	echo "fst_session_oom" >> $ignored_by_lkp
	echo "p2ps_service_discovery_multiple_queries" >> $ignored_by_lkp
	echo "pmksa_cache_preauth_vlan_used_per_sta_vif" >> $ignored_by_lkp
	echo "p2ps_channel_active_go_and_station_different_mcc" >> $ignored_by_lkp
	echo "rfkill_p2p_discovery_p2p_dev" >> $ignored_by_lkp
	echo "scan_only" >> $ignored_by_lkp
	echo "discovery_pd_retries" >> $ignored_by_lkp
	echo "rrm_beacon_req_table_rsne" >> $ignored_by_lkp
	echo "p2p_service_discovery_external" >> $ignored_by_lkp
	echo "wnm_bss_tm_scan_needed" >> $ignored_by_lkp
	echo "wnm_bss_tm_scan_needed_e4" >> $ignored_by_lkp
	echo "wnm_bss_tm_scan_not_needed" >> $ignored_by_lkp
	echo "grpform_no_5ghz_add_cli3" >> $ignored_by_lkp
	echo "grpform_no_5ghz_world_roaming" >> $ignored_by_lkp
	echo "p2ps_connect_adv_go_persistent" >> $ignored_by_lkp
	echo "owe_transition_mode_open_only_ap" >> $ignored_by_lkp
	echo "ap_wpa2_eap_aka_prime_sql" >> $ignored_by_lkp
	echo "ap_wpa2_psk_ext_retry_msg_3" >> $ignored_by_lkp
	echo "ap_wps_er_multi_add_enrollee" >> $ignored_by_lkp
	echo "dpp_ap_config_p384_p384" >> $ignored_by_lkp

	echo "# ignore _wait_for_the_reply_of_community" >> $ignored_by_lkp
	echo "ap_config_reload" >> $ignored_by_lkp
	echo "ap_config_reload_file" >> $ignored_by_lkp
	echo "eap_fast_proto_phase2" >> $ignored_by_lkp
}

install()
{
	build_hwsim_param_long
	build_hwsim_require_mcc

	build_ignored_by_lkp || return

	cd $source_dir
	$LKP_SRC/tools/hwsim-extract-testcase $source_dir/tests/hwsim
	cp -af $source_dir/* $BM_ROOT
}

pack()
{
	{
		echo /usr
		echo /usr/bin
		echo /usr/bin/wmediumd
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
