#!/bin/bash

download()
{
	git_clone_update https://github.com/bcopeland/wmediumd.git || return
	git_clone_update git://w1.fi/srv/git/hostap.git
}

build()
{
	cd ../wmediumd || return
	make || return
	# binary will be installed into /usr/bin/wmediumd
	make install || return
	cd -
	patch_source || return

	# support WPA-EAP-SUITE-B-192, example-wpa_supplicant.config and example-hostapd.config contains support options for build.
	# hostapd_config_parse_key_mgmt() in hostapd/config_file.c will check "CONFIG_SUITEB192".
	# if not set "CONFIG_SUITEB192=y", suite_b_192 can not be added into key_mnt.

	# if example-wpa_supplicant.config and example-hostapd.config not exist, it means hostap(git://w1.fi/srv/git/hostap.git)
	# remove the files, we need to check the option in the new configuration files
	local wpa_supplicant_config="./tests/hwsim/example-wpa_supplicant.config"
	local hostapd_config="./tests/hwsim/example-hostapd.config"

	if [[ -f $wpa_supplicant_config ]]; then
		grep -q -w "CONFIG_SUITEB192=y" $wpa_supplicant_config || echo "CONFIG_SUITEB192=y" >> $wpa_supplicant_config
	else
		echo "Warning: $wpa_supplicant_config not exist, failed to set CONFIG_SUITEB192=y"
	fi
	if [[ -f $hostapd_config ]]; then
		grep -q -w "CONFIG_SUITEB192=y" $hostapd_config || echo "CONFIG_SUITEB192=y" >> $hostapd_config
	else
		echo "Warning: $hostapd_config not exist, failed to set CONFIG_SUITEB192=y"
	fi

	$RUN_QUIET ./tests/hwsim/build.sh
}

build_hwsim_param_long()
{
	# try to find out the case requiring params long
	# root@debian9:/home/lizhijian/chroot/lkp/benchmarks/hwsim/tests/hwsim# git grep -B 2 -w 'if not params\['\'long\']
	# test_ap_ciphers.py-def test_ap_cipher_tkip_countermeasures_sta2(dev, apdev, params):
	# test_ap_ciphers.py-    """WPA-PSK/TKIP countermeasures (detected by two STAs) [long]"""
	# test_ap_ciphers.py:    if not params['long']:

	cd $source_dir/tests/hwsim
	git grep -B 2 -w 'if not params\['\'long\'] | grep '.*\.py\-def' | awk -F 'def ' '{print $2}' | awk -F'(' '{print $1}' | sed s/test_//g > require_long_param
}

build_hwsim_require_under_vm()
{
	# try to find out the case requiring under vm
	# root@debian9:/lkp/benchmarks/hwsim/tests/hwsim# git grep -B 2 -w 'require_under_vm'
	# test_ap_dynamic.py-import hwsim_utils
	# test_ap_dynamic.py-import hostapd
	# test_ap_dynamic.py:from utils import alloc_fail, require_under_vm, get_phy
	# --
	# test_ap_dynamic.py-def test_ap_iapp(dev, apdev):
	# test_ap_dynamic.py-    """IAPP and multiple BSSes"""
	# test_ap_dynamic.py:    require_under_vm()
	cd $source_dir/tests/hwsim
	git grep -B 2 -w 'require_under_vm' | grep '\-def ' | grep -v _test | awk -F' test_' '{print $2}' | awk -F'(' '{print $1}' > require_under_vm
}

build_hwsim_setup_oom()
{
	cd $source_dir/tests/hwsim
	git grep -E -e 'def test.*oom' -e 'def test.*out_of_memory' | awk -F 'test_' '{print $3}'| awk -F '(' '{print $1}' > setup_oom
}

install()
{
	build_hwsim_param_long
	build_hwsim_require_under_vm
	build_hwsim_setup_oom
	cd $source_dir
	$LKP_SRC/tools/hwsim-extract-testcase $source_dir/tests/hwsim
	cp -af $source_dir/* $BM_ROOT
}

pack()
{
	{
		echo /usr
		echo /usr/bin
		echo /usr/bin/wmediumd
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
