#!/bin/bash

filename="iozone3_479"
WEB_URL="http://www.iozone.org/src/current/$filename.tar"

download()
{
	wget $WEB_URL
}

build()
{
	tar vxf $filename.tar
	cd $filename/src/current
	make linux-AMD64
}

install()
{
	for bin in iozone pit_server fileop
	do
		cp $bin ${BM_ROOT}
		ln -sf ${BM_ROOT}/$bin /usr/local/bin/$bin
	done
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		find /lkp/benchmarks/$BM_NAME
		echo /usr/local/bin/iozone
		echo /usr/local/bin/pit_server
		echo /usr/local/bin/fileop
	} |
	cpio --quiet -o -H newc | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
