#!/bin/bash

VERSION="3.0.3"
WEB_URL="http://stats.es.net/software/${BM_NAME}-${VERSION}.tar.gz"

build()
{
	cd "$source_dir"
	LDFLAGS=-Wl,-rpath=$BM_ROOT/lib,--enable-new-dtags ./configure --prefix=$BM_ROOT
	make
}
