#!/bin/bash

download()
{
	source_dir="linux"

	[[ -d linux ]] && return

	[[ -d /c/linux ]] && local opt_ref="--reference /c/linux"

	local cmd="git clone -q $opt_ref https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
	$cmd && return
	$cmd
}

build()
{
	make allyesconfig		|| return
	make prepare			|| return
	cd tools/testing/selftests	|| return
	make				|| return
	# install cpupower command
	cd ../../power/cpupower		|| return
	make 				|| return
	make install			|| return
}

install()
{
	cp -af * $BM_ROOT
}

pack()
{
	{
		echo /usr
		echo /usr/lib
		find /usr/lib/libcpupower.*
		echo /usr/bin
		echo /usr/bin/cpupower
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
	} |
	cpio --quiet -o -H newc | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
