#!/bin/bash

download()
{
	wget --no-clobber https://vilimpoc.org/research/ku-latency/send-data.c
	wget --no-clobber https://vilimpoc.org/research/ku-latency/ku-latency.c
}

build()
{
	gcc -o $BM_ROOT/ku-latency ku-latency.c -lrt -Wall
	gcc -o $BM_ROOT/send-data send-data.c -lrt -Wall
}

install()
{
	:
}

cleanup()
{
	rm "ku-latency.c" "send-data.c"
}
