#!/bin/bash

CONFIGURE_FLAGS="--arch=$arch"

download()
{
	git_clone_update git://git.kernel.org/pub/scm/virt/kvm/kvm-unit-tests.git
	source_dir=$BM_NAME
}

install()
{
	cp -af /tmp/$BM_NAME/* $BM_ROOT/
}
