#!/bin/bash

if [[ $arch ]]; then
	CONFIGURE_FLAGS="--arch=$arch"
elif [[ ! $opt_deb ]]; then
	echo "must specify '-a <arch>' argument"
	exit
fi

download()
{
	git_clone_update git://git.kernel.org/pub/scm/virt/kvm/kvm-unit-tests.git
	source_dir=$BM_NAME
}

install()
{
	cp -af config.mak run_tests.sh x86-run $BM_ROOT

	# remove color character for test result
	sed -i 's/\\e\[[03][12]*m//g' $BM_ROOT/run_tests.sh

	mkdir -p $BM_ROOT/x86
	cp -af x86/*.flat x86/run x86/unittests.cfg $BM_ROOT/x86
}
