#!/bin/bash
download()
{
	git_clone_update https://github.com/libhugetlbfs/libhugetlbfs.git
}

build()
{
	[ "$distro" = "centos" ] && {
		patch -p1 < $LKP_SRC/pack/${BM_NAME}-addon/0001-tests-hugetests.h-fix-compile-errors-under-centos.patch || return
	}
	patch_source || return
}

install()
{
	cp -af $source_dir/. $BM_ROOT/
}

# The libhugetlbfs needs to generate version.h file which includes version info
# based on the info in the .git. But the default pack() can not find .git dirctory.
pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/.
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
