#!/bin/bash

WEB_URL="http://registrationcenter.intel.com/irc_nas/3914/l_lpk_p_11.1.2.005.tgz"
source_dir="linpack_11.1.2"

install()
{
	cd benchmarks/$BM_NAME
	cp -af xlinpack_xeon64 $BM_ROOT
	cp -af runme_xeon64 $BM_ROOT
}
