#!/bin/bash

download()
{
	[ "$distro" != "centos" ] && {
		git_clone_update https://git.centos.org/r/rpms/rusers.git || return
	}
	git_clone_update https://github.com/PeterHuewe/tpm-emulator.git || return
	git_clone_update https://github.com/ianw/numactl.git || return
	git_clone_update https://github.com/linux-test-project/ltp.git
}

split_syscalls()
{
	local cmdfile="runtest/syscalls"
	[ -f "$cmdfile" ] || return 0
	# syscalls_partN file exists, abort splitting
	[ -f "${cmdfile}_part1" ] && return 0

	i=1
	n=1
	cat $cmdfile | sed -e '/^$/ d' -e 's/^[ ,\t]*//' -e '/^#/ d' | while read line
	do
		if [ $n -gt 300 ];then
			i=$(($i+1))
			n=1
		fi
		echo "$line" >> "runtest/syscalls_part${i}"
		n=$(($n+1))
	done

	echo "Splitting syscalls to syscalls_part1, ..., syscalls_part$i"
}

rearrange_dio()
{
	[ -f "dio" ] || return

	sed -e "s/^#.*//g" dio | awk '{if (length !=0) print $0}' >> diocase || return
	sed -n "1,20p" diocase >> dio-00 || return
	sed -n "21,25p" diocase >> dio-01 || return
	sed -n "26,28p" diocase >> dio-02 || return
	sed -n "29,\$p" diocase >> dio-03 || return
	rm diocase || return
}

rearrange_case()
{
	cd ./runtest || return

	# re-arrange the case dio
	rearrange_dio || return

	# re-arrange the case fs_readonly
	[ -f "fs_readonly" ] || return
	split -d -l15 fs_readonly fs_readonly- || return

	cd ..
}

patch_source()
{
	local patch=$LKP_SRC/pack/$1
	[[ -f $patch ]] || return 0
	patch -p1 < $patch
}

build_rusers()
{
	local branch=$(git branch -a | grep /c | tail -1 | awk -F/ '{print $NF}')
	git checkout "$branch" || return

	RUSERS_VERSION=$(grep ^Version: SPECS/rusers.spec | awk '{print $2}')

	local source=$(grep ^Source: SPECS/rusers.spec | awk '{print $2}')
	local url=$(echo $source | sed s/"%{version}"/${RUSERS_VERSION}/g)
	curl -k "$url" -o netkit-rusers.tar.gz

	tar zxf netkit-rusers.tar.gz

	for p in $(grep ^Patch SPECS/rusers.spec | awk '{print $2}')
	do
		echo "Patching $p ..."
		patch -f -p0 < SOURCES/$p
	done

	cd netkit-rusers-$RUSERS_VERSION
	./configure --prefix=$BM_ROOT/netkit-rusers
	cd rup
	make || return
	cd ../../
}

build_tpm_emulator()
{
	# remove Werror to use gcc-7
	sed -i "s/-Werror//g" CMakeLists.txt
	# don't build kernel module
	sed -i "s/add_subdirectory(tpmd_dev)/#add_subdirectory(tpmd_dev)/g" CMakeLists.txt
	mkdir build && cd build
	cmake ..
	make || return
	make install || return
	make package || return
	cd ..
}

build_ltp()
{
	patch_source ltp.patch || return
	patch -p1 < $LKP_SRC/pack/ltp-addon/v2-0001-shmctl-enable-subtest-SHM_LOCK-SHM_UNLOCK-only-if.patch || return
	# fix ltplite:rwtest01-04
	patch -p1 < $LKP_SRC/pack/ltp-addon/0001-Specify-TMPDIR-for-rwtest01-04.patch || return
	# fix commond:ar01
	patch -p1 < $LKP_SRC/pack/ltp-addon/ar_fail.patch || return

	split_syscalls
	rearrange_case || return
	make autotools
	./configure --prefix=$BM_ROOT
	make
}

build_numactl()
{
	autoreconf
	./configure --prefix=$BM_ROOT/testcases/bin/numactl
	make
}

install_rusers()
{
	mkdir -p $BM_ROOT/netkit-rusers/{bin,man/man1}
	cd netkit-rusers-$RUSERS_VERSION/rup
	make install 2> /dev/null
}

install_tpm_emulator()
{
	mkdir -p $BM_ROOT/tpm-emulater
	cp build/*.zip $BM_ROOT/tpm-emulater
}

install_ltp()
{
	make install
	cp testcases/commands/tpm-tools/tpmtoken/tpmtoken_import/tpmtoken_import_openssl.cnf $BM_ROOT/testcases/bin/
	cp testcases/commands/tpm-tools/tpmtoken/tpmtoken_protect/tpmtoken_protect_data.txt  $BM_ROOT/testcases/bin/
	grep -v -w -f $LKP_SRC/pack/ltp-black-list \
	runtest/syscalls > $BM_ROOT/runtest/syscalls
}

install_numactl()
{
	make install
	ln -sf $BM_ROOT/testcases/bin/numactl/bin/numademo $BM_ROOT/testcases/bin/numademo
	ln -sf $BM_ROOT/testcases/bin/numactl/bin/memhog $BM_ROOT/testcases/bin/memhog
}

build()
{
	build_ltp || exit

	cd ../tpm-emulator || exit
	build_tpm_emulator || exit

	cd ../numactl || exit
	build_numactl || exit

	[ "$distro" != "centos" ] && {
		cd ../rusers || exit
		build_rusers || exit
	}
	return 0
}

install()
{
	cd ../ltp || exit
	install_ltp || exit

	cd ../tpm-emulator || exit
	install_tpm_emulator || exit

	cd ../numactl || exit
	install_numactl || exit

	[ "$distro" != "centos" ] && {
		cd ../rusers || exit
		install_rusers || exit
	}
	return 0
}

strip_object_files()
{
	:
}
