#!/bin/bash

download()
{
	git clone https://github.com/linux-test-project/ltp.git
	source_dir=$BM_NAME
}

build()
{
	cd $source_dir
	make autotools
	./configure --prefix=$BM_ROOT
	make
}

install()
{
	make install
	grep -v -w -f $LKP_SRC/pack/ltp-black-list \
	runtest/syscalls > $BM_ROOT/runtest/syscalls
}
