#!/bin/bash

download()
{
	git_clone_update git://git.kernel.org/pub/scm/linux/kernel/git/gong.chen/mce-test.git
	source_dir=$BM_NAME
}

build()
{
	cd $source_dir
	make
}

install()
{
	make install
	cp -af * $BM_ROOT
}
