#!/bin/bash

download()
{
	git_clone_update https://github.com/linux-test-project/ltp.git
	git_clone_update https://git.kernel.org/pub/scm/utils/cpu/mce/mce-inject.git
	git_clone_update git://bee.sh.intel.com:/git/ras.git
	# keep it in the last to set the effective source_dir
	git_clone_update https://git.kernel.org/pub/scm/utils/cpu/mce/mce-test.git
}

build()
{
	patch_source

	make
	make -C ../mce-inject

	cd ../ras
	./mcetest_build.sh
}

install()
{
	make install || return
	cp -af ./* "$BM_ROOT"

	make install -C ../mce-inject || return

	cp -af ../mce-inject/mce-inject "$BM_ROOT"

	cp -af ../ltp "$BM_ROOT"

	cp -af ../ras "$BM_ROOT"
}

pack()
{
	{
		echo /usr
		echo /usr/sbin
		echo /usr/sbin/mce-inject
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/"$BM_NAME"
		find /lkp/benchmarks/"$BM_NAME"/*
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/"${BM_NAME}".cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
