#!/bin/bash

download()
{
	git_clone_update git://git.kernel.org/pub/scm/linux/kernel/git/gong.chen/mce-test.git
	git_clone_update git://git.kernel.org/pub/scm/utils/cpu/mce/mce-inject.git
	source_dir=$BM_NAME
}

build()
{
	make -C /tmp/mce-test
	make -C /tmp/mce-inject
}

install()
{
	cd /tmp/mce-test
	make install
	cp -af * $BM_ROOT
	cp -af /tmp/mce-inject/mce-inject $BM_ROOT
}
