#!/bin/bash

download_mdadm_release()
{
	local download_site="https://www.kernel.org/pub/linux/utils/raid/mdadm/"
	local download_file=""

	download_file=$(curl -s -k $download_site | grep "mdadm.*tar.xz" | cut -d '"' -f 2 | tail -1)
	curl -s -k $download_site$download_file -o $download_file || return
	tar Jxf $download_file || return
	mv ${download_file%.tar.xz} mdadm
	source_dir=$(pwd)/mdadm
	cd mdadm
	git init
}

download()
{
	git_clone_update git://git.neil.brown.name/mdadm.git || download_mdadm_release
}

build()
{
	# make failed when using gcc-7, no error with using gcc-6.
	sed -i "s/CWFLAGS = -Wall -Werror/CWFLAGS = -Wall/" Makefile

	patch_source || return

	make test
}

install()
{
	cp -a $source_dir/* $BM_ROOT/
}
