#!/bin/bash

download()
{
	git_clone_update git://git.neil.brown.name/mdadm.git
}

build()
{
	sed -i "s/^test: mdadm mdmon test_stripe swap_super raid6check/^test: mdadm mdmon test_stripe swap_super/"  Makefile
	make test
}

install()
{
	cp -a $source_dir/* $BM_ROOT/
}
