#!/bin/bash

VERSION="2.7.0"
WEB_URL="ftp://ftp.netperf.org/netperf/netperf-${VERSION}.tar.gz"

build()
{
	local configure_flags=(
				--prefix=$BM_ROOT
				--enable-demo
				--enable-unixdomain
				--enable-sctp
				--enable-dccp
				--enable-burst
	)
	if [[ $distro == "centos" ]]; then
		CC=gcc ./configure "${configure_flags[@]}"
	else
		CC=gcc-4.9 ./configure "${configure_flags[@]}"
	fi
	make
}
