#!/bin/bash

download()
{
	git_clone_update https://github.com/akopytov/sysbench || return
}

build()
{
	./autogen.sh
	# running sysbench may get "Illegal instruction" error
	# on some arches so avoid it by --without-gcc-arch
	./configure --without-gcc-arch
	make
}

install()
{
	export DESTDIR=$BM_ROOT/sysbench
	make install
	cp -af $source_dir/* $BM_ROOT/sysbench
}
