#!/bin/bash

download()
{
	git_clone_update https://github.com/google/packetdrill.git
}

build()
{
	patch_source || return
	cd $source_dir/gtests/net/packetdrill
	sed -i 's/gettid(/packetdrill_gettid(/g' run_system_call.c
	./configure
	make
}

install()
{
	cp -af $source_dir/* $BM_ROOT
}
