#!/bin/bash

download()
{
	git_clone_update https://github.com/google/packetdrill.git
	source_dir="packetdrill"
}

build()
{
	cd $source_dir/gtests/net/packetdrill
	./configure
	make
}

install()
{
	cp -af /tmp/$source_dir/* $BM_ROOT
}
