#!/bin/bash

download()
{
	git_clone_update https://github.com/google/packetdrill.git
}

build()
{
	cd $source_dir/gtests/net/packetdrill
	./configure
	make
}

install()
{
	cp -af $source_dir/* $BM_ROOT
}
