#!/bin/bash

PBZIP2_VER=1.1.9
WEB_URL="https://launchpad.net/pbzip2/1.1/1.1.9/+download/pbzip2-$PBZIP2_VER.tar.gz"

install()
{
	make install || return
	touch /lkp/benchmarks/$BM_NAME/empty
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
		echo /usr/bin
		echo /usr/bin/pbzip2
		echo /usr/bin/pbunzip2
		echo /usr/bin/pbzcat
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
