#!/bin/bash

. $LKP_SRC/lib/run-env.sh

download()
{
	[[ -d linux ]] || {
		local linux_git=${GIT_WORK_TREE:-${LKP_GIT_WORK_TREE:-$(git_root_dir)/linux}}
		[[ -d $linux_git ]] && local opt_ref="--reference $linux_git"
		git clone -q $opt_ref https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git || return
	}
	source_dir="linux"
}

build()
{
	cd tools/perf

	[ "$distro" = "clear" ] && ln -sf /usr/bin/ld.gold $BUILD_DIR/ld
	PATH=$BUILD_DIR:$PATH make
}

install()
{
	cp -af perf $BM_ROOT
}
