#!/bin/bash

. $LKP_SRC/lib/env.sh

download()
{
	git_clone_update git://github.com/waffle-gl/waffle
	git_clone_update git://anongit.freedesktop.org/xorg/app/intel-gpu-tools
	# keep it in the last to set the effective source_dir
	git_clone_update git://anongit.freedesktop.org/piglit
}

find_delete_files()
{
	find $1 -name '*.c' -or -name '*.o' -delete
}

build()
{
	# apt-get build-dep intel-gpu-tools
	# apt-get install libglu1-mesa-dev python3-dev

	local ncpu=$(nproc)
	local wayland=1

	[ "$distro" = "centos" ] && wayland=0
	cd ../waffle || return
	cmake	-Dwaffle_has_glx=1	\
		-Dwaffle_has_x11_egl=1	\
		-Dwaffle_has_wayland=$wayland	\
		-Dwaffle_has_gbm=1	\
		-DCMAKE_INSTALL_PREFIX=/usr || return
	make || return
	make install || return
	find_delete_files || return

	cd ../$BM_NAME || return
	cmake -DCMAKE_INSTALL_PREFIX=$BM_ROOT || return
	make || return
	make install || return
	find_delete_files || return


	cd ../intel-gpu-tools || return
	[ "$distro" = "centos" ] && local opts="--disable-amdgpu"
	./autogen.sh $opts || return
	make || return
	find_delete_files
}

create_config()
{
	cat > /lkp/benchmarks/piglit/piglit.conf <<-EOF
	[igt]
	path=$BM_ROOT/lib/piglit/bin/igt
	EOF
}

install()
{
	cd $source_dir || return
	mv -T ../intel-gpu-tools $BM_ROOT/lib/$BM_NAME/bin/igt

	create_config
	generate_test_groups
}

generate_test_groups()
{
	(
	cd $BM_ROOT || exit
	mkdir -p groups

	local tset
	for tset in sanity igt all quick
	do
		# the output like below:
		# running: spec/!opengl 1.1/streaming-texture-leak
		#
		# using `sed` command may result in some errors, it is due to exist some special character such as "!"
		bin/piglit run $tset /tmp/piglit-output -d -v | grep 'running:' | cut -f2- -d":" | tr -d " " > groups/$tset-all
	done
	)
}

pack()
{
	{

		echo /lkp
		echo /lkp/benchmarks
		find /lkp/benchmarks/$BM_NAME
		find /usr/lib/x86_64-linux-gnu/libwaffle-1.so*
	} |
	cpio --quiet -o -H newc | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"

}

post_cleanup()
{
	rm -fr "$source_dir"
}
