#!/bin/bash

download()
{
	git_clone_update https://github.com/vasi/pixz.git

}

build()
{
	./autogen.sh || return
	./configure || return
	make
}

install()
{
	make install || return
	touch /lkp/benchmarks/$BM_NAME/empty
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
		echo /usr/local
		echo /usr/local/bin
		echo /usr/local/bin/pixz
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
