#!/bin/bash

PLZIP_VER=1.4
SRC_URL="http://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-1.5.tar.gz \
         http://download.savannah.gnu.org/releases/lzip/plzip/plzip-$PLZIP_VER.tar.gz"

download()
{
	for url in $SRC_URL
	do
		wget -t 3 -T 60 --no-clobber $url
		source_package=$(basename $url)
		source_dir=${source_package%%.tar.*}
		tar xf "$source_package"
	done
}

build()
{
	cd ../lzlib-1.5 || return
	./configure || return
	make || return
	make install || return
	cd ../plzip-$PLZIP_VER || return
	./configure || return
	make LDFLAGS="-L/usr/local/lib"
}

install()
{
	make install || return
	touch /lkp/benchmarks/$BM_NAME/empty
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
		echo /usr/local
		echo /usr/local/bin
		echo /usr/local/bin/plzip
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
