#!/bin/bash

download()
{
	git_clone_update https://github.com/glmark2/glmark2.git || return
	git_clone_update https://git.linaro.org/power/pm-qa.git
}

install()
{
	make -C cpuidle cpuidle_killer
	cp -af $source_dir/* $BM_ROOT

	[ "$distro" = "clear" ] && return

	cd ../glmark2

	# https://unix.stackexchange.com/questions/265668/g-doesnt-recognize-standard-14-std-c14
	# [ 1/67] Compiling src/main.cpp
	# g++: error: unrecognized command line option ‘-std=c++14’
	[ "$distro" = "centos" ] && sed -i 's/-std=c++14/-std=c++1y/' wscript
	./waf configure --prefix=$BM_ROOT/glmark2 --with-flavors=x11-gl || return
	./waf || return
	./waf install || return
}
