#!/bin/bash

pre_download()
{
	wget -q -O ${BM_NAME}-latest.txt "https://www.openfabrics.org/downloads/qperf/latest.txt"
	WEB_URL="https://www.openfabrics.org/downloads/${BM_NAME}/$(<${BM_NAME}-latest.txt)"
}

install()
{
	cp -af src/$BM_NAME $BM_ROOT
}
