#!/bin/bash

VERSION="7.0.1.13"
WEB_URL="https://sourceforge.net/projects/re-aim-7/files/re-aim/${VERSION}/osdl-aim-${VERSION}.tar.gz/download"
source_dir="osdl-aim-7"

build()
{
	patch_source
	./bootstrap
	LDFLAGS=-laio \
	./configure --prefix=$BM_ROOT
	make
}

install()
{
	cp -af src/reaim $BM_ROOT
	cp -af data $BM_ROOT
	cp -af scripts $BM_ROOT
}
