#!/bin/bash

download()
{
	git_clone_update https://github.com/Mellanox/sockperf.git
}

build()
{
	git checkout -q -b build origin/sockperf_v2
	./autogen.sh
	./configure
	make
}

install()
{
	cp -af /tmp/$source_dir/* $BM_ROOT
}
