#!/bin/bash

NAME=stress-ng
VERSION=0.09.58
WEB_URL="http://kernel.ubuntu.com/~cking/tarballs/stress-ng/${NAME}-${VERSION}.tar.xz"
download()
{
	wget -O ${BM_NAME} $WEB_URL
}

build()
{
	tar xvJf ${BM_NAME}
	cd ${NAME}-${VERSION}
	make
}

install()
{
	make install
}
