#!/bin/bash

download()
{
	git_clone_update https://git.samba.org/sahlberg/dbench.git
}

build()
{
	./autogen.sh || return
	./configure || return
	# Fix libnfs.c:27:39: error: intptr_t undeclared (first use in this function); did you mean in_port_t?
	sed -i '/#include "nfs.h/a #include <stdint.h>' libnfs.c
	make dbench || return
	make tbench || return
	make tbench_srv
}

install()
{
	make install || return
	cp -a tbench tbench_srv /usr/local/bin
	cp -a /usr/local/share/doc/dbench/loadfiles/* /usr/local/share/
	touch /lkp/benchmarks/$BM_NAME/empty
}

pack()
{
	{
		echo /lkp
		echo /lkp/benchmarks
		echo /lkp/benchmarks/$BM_NAME
		find /lkp/benchmarks/$BM_NAME/*
		echo /usr/local
		echo /usr/local/bin
		echo /usr/local/bin/dbench
		echo /usr/local/bin/tbench
		echo /usr/local/bin/tbench_srv
		echo /usr/local/share
		echo /usr/local/share/client.txt
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > /lkp/benchmarks/${BM_NAME}.cgz
	[[ $arch ]] && mv "/lkp/benchmarks/${BM_NAME}.cgz" "/lkp/benchmarks/${BM_NAME}-${arch}.cgz"
}
