#!/bin/bash

VERSION="0.9"
WEB_URL="http://jaist.dl.sourceforge.net/project/${BM_NAME}/${BM_NAME}/${VERSION}/${BM_NAME}-${VERSION}.tar.gz"
build()
{
	cp /usr/share/misc/config.{guess,sub} .
	./configure --prefix=$BM_ROOT
	make
}
