#!/bin/bash

download()
{
	git_clone_update https://github.com/kdlucas/byte-unixbench.git
}

build()
{
	cd $source_dir || return
	patch_source
	cd UnixBench
	make
}

install()
{
	cp -af $source_dir/* $BM_ROOT
	mkdir $BM_ROOT/results
}
