#!/bin/bash

cd /lkp/benchmarks/piglit
mkdir -p groups

for tset in all igt sanity quick
do
	bin/piglit run $tset /tmp/piglit-output -d -v | grep 'running ::' | sed 's/running :: //' > groups/$tset-all

	cd groups
	[[ -f $tset-000 ]] || split -d -a3 -l100 $tset-all $tset-
	cat ${tset}-[0-9]* > $tset-all-known
	grep -v -x -F -f $tset-all-known $tset-all > $tset-new
	cat $tset-new >> $tset-000
	rm $tset-all $tset-all-known $tset-new
	cd ..
done
