#!/bin/bash

download()
{
	git_clone_update https://git.kernel.org/pub/scm/linux/kernel/git/wfg/vm-scalability.git
	source_dir="vm-scalability"
}

build()
{
	cd $source_dir 
	make all
}

install()
{
	cp -af * $BM_ROOT
}
