#!/bin/bash

download()
{
	git_clone_update https://git.kernel.org/cgit/linux/kernel/git/wfg/vm-scalability.git/
	source_dir="vm-scalability"
}

build()
{
	cd $source_dir 
	make all
}

install()
{
	find . -maxdepth 1 -type f -executable ! -name ".*" \
		-exec cp -af {} $BM_ROOT \;
}
