#!/bin/bash

download()
{
	git_clone_update git://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git
	git_clone_update git://oss.sgi.com/xfs/cmds/xfsprogs
}

build()
{
	make || return
	make install-dev

	cd ../xfstests-dev
	patch_source || return
	## Currently, ./configure file can't work with "--prefix" option correctly,
	## so we just use the "make" command to generate the execuable file.
	make
}

install()
{
	cp -af $source_dir/* $BM_ROOT/
	cp -af $LKP_SRC/pack/${BM_NAME}-addon/* $BM_ROOT/

	## generate the new add subcase automatically after every upgrade xfstests
	cd $BM_ROOT/tests
	./update-new-cases.sh ext4
	./update-new-cases.sh btrfs
	./update-new-cases.sh xfs
	./update-new-cases.sh generic
}
