#!/bin/bash

source $LKP_SRC/lib/result.sh

shopt -s nullglob

remove_from_mrtts()
{
    local dir=$1
    is_mrt $dir && echo $dir | lkp delete_mrts
}

remove()
{
	local temp_file_unsort=$(mktemp)
	cleanup_path_record_from_patterns $patterns > $temp_file_unsort || exit

	[[ -s "$temp_file_unsort" ]] ||
	{
		rm -f $temp_file_unsort
		echo "Cannot find the match _result_root according to the patterns: $patterns" >&2
		exit 1
	}

	local temp_file_sort=$(mktemp)
	awk -F'/' '{OFS="/"; NF=NF-2; print}' $temp_file_unsort | sort -u > $temp_file_sort

	local path
	while read path
	do
		remove_from_mrtts $path
	done < $temp_file_sort

	cat $temp_file_sort | xargs rm -rf

	rm -f $temp_file_unsort
	rm -f $temp_file_sort
}

usage()
{
	cat >&2 <<-EOF
Usage:
	lkp $script_name <patterns>
Example:
	lkp $script_name /xfstests/ /lkp-ws02/ /v4.3/
EOF
	exit 1
}

script_name=$(basename $0)
[[ $# = 0 ]] && usage

patterns="$*"

echo -n "!!! Do you really want to do that? [No/yes]: "
read answer
if [[ $answer = "yes" ]]; then

	remove

	echo "Done" >&2
fi

