#!/bin/bash

rc_file=$(tempfile --prefix=lkp-)
trap "rm -rf $rc_file" EXIT

for lib in misc.sh job-init.sh bootstrap.sh job.sh env.sh; do
	echo ". $LKP_SRC/lib/$lib" >> $rc_file
done

ENV=$rc_file dash
