#!/usr/bin/env ruby

LKP_SRC ||= ENV['LKP_SRC']

require "#{LKP_SRC}/lib/result_root"

def main
  $stdin.each_line do |mrtp|
    mrtp = mrtp.strip
    next unless File.exist? mrtp
    delete_mrt mrtp
  end
end

main
