#!/bin/bash

source $LKP_SRC/lib/common.sh

shopt -s nullglob

is_rt()
{
	local path=$1
	local bn=$(basename $path)
	local dn=$(dirname $path)
	[[ $bn =~ [0-9]+ ]] &&
		[[ -f $path/job.yaml ]] &&
		[[ -f $dn/stddev.json ]]
}

check_rt()
{
	local path=${1%%/}
	local dn=$(dirname $path)
	grep -q $path/stats.json $dn/matrix.json
}

remove()
{
	for path; do
		path=$(abs_path $path)
		echo sed -i \'"/${path//\//\\/}/d"\' "/lkp/paths/*"
		echo rm -fr "$path"
	done
}

is_mrt()
{
	local dir=$1
	local -a jobs
	local -a matrix
	matrix=( $dir/matrix.json* )
	[ ${#matrix} -eq 0 ] && return 1
	jobs=( $dir/[0-9]*/job.yaml )
	[ ${#jobs} -ge 1 ]
}

remove_from_mrtts()
{
	local path
	local dir
	for path; do
		path=$(abs_path $path)
		for dir in $(find $path -type d); do
			is_mrt $dir && echo $dir
		done | lkp delete_mrts
	done
}

echo "The command to remove the result path are:"
remove "$@"
echo -n "!!! Do you really want to do that? [No/yes]: "
read answer
if [[ $answer = "yes" ]]; then
	if is_rt $path && check_rt $path; then
		lkp reprocess -d $path
		while check_rt $path; do
			sleep 10
		done
	fi
	remove_from_mrtts "$@"
	remove "$@" | bash
fi
