#!/bin/bash
# - scaling_governor

[ -d '/sys/devices/system/cpu/cpu0/cpufreq' ] || exit 0
[ "$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver)" = "acpi-cpufreq" ] || exit 0

[ -n "$scaling_governor" ] || scaling_governor=performance

for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
do
	note "echo $scaling_governor > $file"
	echo $scaling_governor > $file
done
