#!/bin/sh -e
# - scaling_max_freq
# - scaling_min_freq

[ -n "$scaling_max_freq" ] || [ -n "$scaling_min_freq" ] || exit 0

. $LKP_SRC/lib/reproduce-log.sh

[ ${scaling_max_freq%%%} != $scaling_max_freq ] && {
	cpuinfo_max_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
	scaling_max_freq=${scaling_max_freq%%%}
	scaling_max_freq=$(( cpuinfo_max_freq * scaling_max_freq / 100 ))
}

log_echo "
	for i in \$(seq 0 \$((\$(nproc)-1)))
	do
		[ -n "scaling_max_freq" ] && echo $scaling_max_freq > /sys/devices/system/cpu/cpu\$i/cpufreq/scaling_max_freq
		[ -n "scaling_min_freq" ] && echo $scaling_min_freq > /sys/devices/system/cpu/cpu\$i/cpufreq/scaling_min_freq
	done
"

for i in $(seq 0 $((nr_cpu-1)))
do
	d_cpu=/sys/devices/system/cpu/cpu$i

	online=1
	[ -f $d_cpu/online ] && online=$(cat $d_cpu/online)
	[ $online -eq 0 ] && continue
	[ "$scaling_max_freq" = "base_freq" ] && scaling_max_freq=$(cat $d_cpu/cpufreq/base_frequency)
	[ "$scaling_min_freq" = "base_freq" ] && scaling_min_freq=$(cat $d_cpu/cpufreq/base_frequency)
	[ -n "scaling_max_freq" ] && echo $scaling_max_freq > $d_cpu/cpufreq/scaling_max_freq
	[ -n "scaling_min_freq" ] && echo $scaling_min_freq > $d_cpu/cpufreq/scaling_min_freq
done
