#!/bin/sh -e

scaling_governor=$1
[ -n "$scaling_governor" ] || exit 0

[ "$(virt-what)" = 'kvm' ] && exit 0

for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
do
	note "echo $scaling_governor > $file"
	      echo $scaling_governor > $file
done
