#!/bin/sh -e
# - offline_cpus
# - offline_package
# - online_cpus

. $LKP_SRC/lib/reproduce-log.sh

# online_cpus overrides the denied list
if [ ! -z $online_cpus ]
then
	cpu_id=0
	d_cpu=/sys/devices/system/cpu/cpu$cpu_id
	while [ -d $d_cpu ]
	do
		match_cpu=false
		for i in $online_cpus
		do
			if [ $i -eq $cpu_id ]
			then
				match_cpu=true
				break
			fi
		done
		if [ "$match_cpu" = "false" ]
		then
			if [ -f $d_cpu/online ]
			then
				echo 0 > $d_cpu/online
				echo CPU$cpu_id offlined
			else
				echo CPU$cpu_id can not be offlined
			fi
		else
			[ -f $d_cpu/online ] && echo 1 > $d_cpu/online
		fi
		sleep 1
		cpu_id=$(( $cpu_id + 1 ))
		d_cpu=/sys/devices/system/cpu/cpu$cpu_id
	done

	sleep 3
	exit 0
fi

if [ ! -z $offline_cpus ]
then
	for i in $offline_cpus
	do
		d_cpu=/sys/devices/system/cpu/cpu$i

		[ -f $d_cpu/online ] || { echo CPU$i can not be offlined; exit 1; }

		echo 0 > $d_cpu/online
		echo CPU$i offlined
		sleep 1
	done
fi

if [ ! -z $offline_package ]
then
	cpu_id=0
	d_cpu=/sys/devices/system/cpu/cpu$cpu_id
	while [ -d $d_cpu ]
	do
		online=1
		[ -f $d_cpu/online ] && online=$(cat $d_cpu/online)
		if [ $online -eq 1 ]
		then
			package_id=$(cat $d_cpu/topology/physical_package_id)
			if [ "$package_id" = "$offline_package" ]
			then
				[ -f $d_cpu/online ] || { echo CPU$cpu_id can not be offlined; exit 1; }
				echo 0 > $d_cpu/online
				echo CPU$cpu_id offlined
				sleep 1
			fi
		fi
		cpu_id=$(( $cpu_id + 1 ))
		d_cpu=/sys/devices/system/cpu/cpu$cpu_id
	done
fi
sleep 3
