#!/bin/sh
# - dirty_ratio
# - dirty_bytes
# - dirty_background_ratio
# - dirty_background_bytes

. $LKP_SRC/lib/reproduce-log.sh

if [ -n "$dirty_ratio" ]; then
	log_eval "echo $dirty_ratio > /proc/sys/vm/dirty_ratio"
elif [ -n "$dirty_bytes" ]; then
	log_eval "echo $dirty_bytes > /proc/sys/vm/dirty_bytes"
fi

if [ -n "$dirty_background_ratio" ]; then
	log_eval "echo $dirty_background_ratio > /proc/sys/vm/dirty_background_ratio"
elif [ -n "$dirty_background_bytes" ]; then
	log_eval "echo $dirty_background_bytes > /proc/sys/vm/dirty_background_bytes"
fi
