#!/bin/sh
# - eatmem_size
# - eatmem_duration
# - eatmem_nonuma

USEMEM=/lkp/benchmarks/vm-scalability/usemem
[ -x $USEMEM ] ||
USEMEM=/lkp/benchmarks/eatmem/usemem

nr_node=$(echo /sys/devices/system/node/node[0-9]* | wc -w)

[ -z "$eatmem_size" ] && die "eatmem: eatmem_size required"
[ -z "$eatmem_duration" ] && eatmem_duration=$((3600*24))

if [ -z "$eatmem_nonuma" ]; then
	for i in $(seq 0 $((nr_node-1))); do
		numactl -m $i -N $i $USEMEM $((eatmem_size/nr_node)) --detach --sleep $eatmem_duration -p $TMP/eatmem_$i.pid
		cat $TMP/eatmem_$i.pid >> $TMP/pid-monitor-eatmem
		rm $TMP/eatmem_$i.pid
	done
else
	$USEMEM $eatmem_size --detach --sleep $eatmem_duration -p $TMP/pid-monitor-eatmem
fi
