#!/bin/bash
# - agent_threads
# - memcached_memsize

. "$LKP_SRC/lib/unit.sh"
. "$LKP_SRC/lib/reproduce-log.sh"

: "${memcached_memsize:=$(to_mb 64m)}"

run_agent()
{
	if [ -n "$agent_threads" ] && [ "$agent_threads" -ne "0" ]; then
		log_cmd /usr/local/bin/mutilate -T "$agent_threads" -A &
	fi
}

log_cmd memcached -d -P /tmp/memcached.pid -m "$(to_mb "$memcached_memsize")" -u root

run_agent
