#!/bin/sh

setup_mysql()
{
	systemctl stop mariadb.service

	# datadir in rootfs too small to meet mysql requriments
	# /etc/init.d/mysql: ERROR: The partition with /lkp/lkp/src/tmp/mysql is too full! ... failed!
	mkdir -p $TMP/mysql
	mount -t tmpfs mysql $TMP/mysql

	# fix "Neither host 'lkp-bdw-ex1' nor 'localhost'
	# could be looked up with '/usr/sbin/resolveip'"
	# from mysql_install_db on Debian.
	[ ! -x /usr/sbin/resolveip ] && \
	ln -s $(which resolveip) /usr/sbin/resolveip

	mysql_install_db --datadir="$TMP/mysql" --user=mysql

	# fix "FATAL: error 1040: Too many connections"
	local max_conn=100
	if [ -n "$nr_threads" ] && [ "$nr_threads" -gt 100 ]; then
		max_conn=$((nr_threads * 2))
	elif [ -n "$nr_task" ] && [ "$nr_task" -gt 100 ]; then
		max_conn=$((nr_task * 2))
	fi

	# /usr/libexec/mysqld is used on RHEL/Centos
	# /usr/bin/mysql is used on Debian/Ubuntu
	# /usr/bin/haswell/mysql is used on Clear Linux
	local exec_mysqld='mysqld'
	mysqld --version >/dev/null 2>&1 || exec_mysqld='/usr/libexec/mysqld'
	$exec_mysqld --datadir="$TMP/mysql" --max-connections="$max_conn" --skip-grant-tables --user=mysql &
}

setup_mysql
