#!/bin/sh

setup_mysql()
{
	[ -s /etc/mysql/my.cnf ] && rm /etc/mysql/my.cnf
	ln -s /etc/mysql/conf.d/mysql.cnf /etc/mysql/my.cnf
	# datadir in rootfs too small to meet mysql requriments
	sed -i "s /var/lib/mysql $TMP/mysql g" /etc/mysql/*.cnf /etc/mysql/*conf.d/*.cnf

	cat > /etc/mysql/conf.d/skip-grant-tables.cnf <<EOF
[mysqld]
skip-grant-tables
EOF

	# FATAL: error 1040: Too many connections
	set_max_connections
	# /etc/init.d/mysql: ERROR: The partition with /lkp/lkp/src/tmp/mysql is too full! ... failed!
	mkdir -p $TMP/mysql
	mount -t tmpfs mysql $TMP/mysql

	cp -a     /var/lib/mysql $TMP/

	mkdir -p /var/lib/mysql-files
	/usr/sbin/mysqld --initialize

	/etc/init.d/mysql start
}

set_max_connections()
{
	# mysql default max_connections is 100
	local max_conn=100
	[ $nr_threads -gt 100 ] && max_conn=$((nr_threads * 2))
	echo max_connections=$max_conn >> /etc/mysql/conf.d/mysqldump.cnf
}

setup_mysql
