#!/bin/bash
# = all
# = localalloc
# = interleave
# = membind
# = cpunodebind
# = preferred

opts=
[ -v "$all"		] && opts+=" --all"
[ -v "$localalloc"	] && opts+=" --localalloc"
[ -n "$interleave"	] && opts+=" --interleave=$interleave"
[ -n "$membind"		] && opts+=" --membind=$membind"
[ -n "$cpunodebind"	] && opts+=" --cpunodebind=$cpunodebind"
[ -n "$preferred"	] && opts+=" --preferred=$preferred"

cat >> $TMP/env.yaml <<EOF

# setup/numactl
exec_prefix: "numactl $opts --"
EOF
