#!/bin/sh
# = all
# = localalloc
# = interleave
# = membind
# = cpunodebind
# = preferred

opts=
[ -v "$all"		] && opts="${opts} --all"
[ -v "$localalloc"	] && opts="${opts} --localalloc"
[ -n "$interleave"	] && opts="${opts} --interleave=$interleave"
[ -n "$membind"		] && opts="${opts} --membind=$membind"
[ -n "$cpunodebind"	] && opts="${opts} --cpunodebind=$cpunodebind"
[ -n "$preferred"	] && opts="${opts} --preferred=$preferred"

cat >> $TMP/env.yaml <<EOF

# setup/numactl
exec_prefix: "numactl $opts --"
EOF
