#!/bin/sh
# - mode
# - nr_pmem

. "$LKP_SRC"/lib/nvdimm.sh

probe()
{
	case "$mode" in
		raw|fsdax)
			parts=$(ls /dev/pmem*)
			nr_part=$(echo $parts | wc -w)
			;;
		dax)
			parts=$(ls /dev/dax*)
			nr_part=$(echo $parts | wc -w)
			;;
		*)
			echo "Invalid nvdimm mode: $mode!" >&2
			exit 1
			;;
	esac
}

check()
{
	if [ -z "$nr_part" ] || [ "$nr_part" -eq 0 ]; then
		echo "No $mode devices found!" >&2
		exit 1
	fi

	[ "$nr_part" -lt "$nr_pmem" ] && {
		echo "No enough $mode devices found: asked $nr_pmem, got $nr_part"
		exit 1
	}

	parts=$(echo $parts | cut "-f1-$nr_part" -d' ')
}

: ${mode:=dax}

configure_nvdimm
probe
check

cat >> $TMP/env.yaml <<EOF

# setup/nvdimm
nr_partitions: $nr_part
partitions: $parts
disk_description: NVDIMM devices
EOF
