#!/bin/sh
# - runtime
# - nr_threads
# - table_size

## OLTP (On-line Transaction Processing) is characterized by a large
## number of short on-line transactions (INSERT, UPDATE, DELETE).
## The main emphasis for OLTP systems is put on very fast query
## processing, maintaining data integrity in multi-access
## environments and an effectiveness measured by number
## of transactions per second.

[ -n "$runtime" ] || runtime=600
[ -n "$table_size" ] && arg_table_size="--oltp-table-size=$table_size"
export PATH=$BENCHMARK_ROOT/$testcase/sysbench/usr/local/bin:$PATH

args="\
	--mysql-user=root\
	--mysql-db=mysql\
	--oltp-read-only=on\
	--max-requests=0\
	--num-threads=$nr_threads\
	--max-time=$runtime\
	$arg_table_size\
"

prepare()
{
	log_cmd sysbench --test=oltp ${args} prepare
}


prepare

cat > "$TMP_RESULT_ROOT"/run.oltp <<EOF
log_cmd sysbench --test=oltp $args run
/etc/init.d/mysql stop
EOF
