#!/bin/sh
# - nr_processes
if [ -n "$mount_points" ]; then
	MONGODB_DIR="${mount_points%% *}"
else
	echo "Can not get the mount points, exit!" 1>&2
	exit 1
fi

for i in $(seq 1 "$nr_processes")
do
	mkdir -p "$MONGODB_DIR/mongodb/dbdir_$i"
	port=$((27016 + i))
	cat > "$TMP_RESULT_ROOT/mongod.conf.$i" <<EOF
# for documentation of all options, see:
# http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
 dbPath: $MONGODB_DIR/mongodb/dbdir_$i
 journal:
  enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
 destination: file
 logAppend: true
 path: $MONGODB_DIR/mongodb/dbdir_$i/mongod.log

# network interfaces
net:
 port: $port
#  bindIp: 127.0.0.1
EOF
done
