#!/bin/sh
# - thp_enabled
# - thp_defrag

if [ -n "$thp_enabled" ]; then 
	echo $thp_enabled >/sys/kernel/mm/transparent_hugepage/enabled
fi
if [ -n "$thp_defrag" ]; then
	echo $thp_defrag >/sys/kernel/mm/transparent_hugepage/defrag
fi
