#!/bin/sh
# - thp_mode
# - thp_defrag

if [ -n "$thp_mode" ]; then 
	echo $thp_mode >/sys/kernel/mm/transparent_hugepage/enabled
fi
if [ -n "$thp_defrag" ]; then
	echo $thp_defrag >/sys/kernel/mm/transparent_hugepage/defrag
fi
