#!/bin/bash

[ -n "$LKP_SRC" ] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

rootfs=$1
[[ $rootfs ]] || rootfs=$(readlink -e /osimage/debian/latest)
[[ $rootfs ]] || {
	echo "What rootfs should I build packages for?"
	exit 1
}

. $LKP_SRC/distro/common

# create cgz for the below jobs first, to avoid circular dependency
$LKP_SRC/sbin/pack-deps $rootfs pack-deps	|| exit
$LKP_SRC/sbin/pack-deps $rootfs pack		|| exit

queue pack-deps.yaml	rootfs=$rootfs benchmark="$(show_deps_list)"
queue pack.yaml		rootfs=$rootfs benchmark="$(show_pack_list)"
