#!/bin/bash

phoronix-test-suite list-available-suites | tee /tmp/pst:list-available-suites
grep -E -o '\<pts/[a-z0-9-]+\>' /tmp/pst:list-available-suites > /tmp/pst:available-suites

pst()
{
	local action=$1

	for suite in $(</tmp/pst:available-suites)
	do
		echo \
		phoronix-test-suite $action $suite
		phoronix-test-suite $action $suite
	done
}

pst install-dependencies
pst batch-install
