#!/bin/bash

# Filter context1 from unixbench on some testboxes, where it always failed due to error:
# 	Run: "Pipe-based Context Switching": slave write failed: Broken pipe; aborting

[[ "$test" == "context1" ]] && {
	declare -A tbox_to_disable=(
		[lituya]=1
		[nhm-white]=1
	)
	[[ ${tbox_to_disable[$testbox]} == 1 ]] && {
		echo "rm $job_file due to $test are known to fail on $testbox"
		exit 1
	}
}

exit 0
