#!/usr/bin/env ruby

require 'yaml'

RESULT_ROOT = ENV['RESULT_ROOT']

exit unless File.exist?("#{RESULT_ROOT}/results/default/status.json")
status = YAML.load_file("#{RESULT_ROOT}/results/default/status.json")

if status['operations'].empty?
  $stderr.puts 'Test environment is not able'
  exit
end

nr_test = 0
status['operations'].each do |op|
  puts "#{op['subdir']}.fail: 1" if op['status_code'] != 'GOOD'
  nr_test += 1
end

puts "total_test: #{nr_test}"
