#!/usr/bin/env ruby
require_relative '../lib/log'

while (line = STDIN.gets)
  case line.chomp!
  when /^(.*): +(\d+) kB$/,
       /^(.*): +(\d+) KiB$/,
       /^(.*): +(\d+)$/
    puts $1 + ': ' + $2
  else
    log_error "malformed meminfo line: #{line}"
  end
end
