#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.reapath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/string_ext"

def show_dmesg_times
  dmesg = "#{ENV['RESULT_ROOT']}/kmsg"
  return unless File.exist? dmesg

  dhcp = false

  File.open(dmesg).each do |line|
    line = line.remediate_invalid_byte_sequence(replace: '_') unless line.valid_encoding?
    case line
    when /\[ *(\d+\.\d+)\] Sending DHCP requests/
      unless dhcp
        puts 'dhcp: ' + $1
        dhcp = true
      end
    when /\[ *(\d+\.\d+)\] Freeing unused kernel memory:/
      puts 'kernel_boot: ' + $1
      break
    end
  end
end
show_dmesg_times

if (line = STDIN.gets)
  boot, idle = line.split
  puts 'boot: ' + boot
  puts 'idle: ' + idle
end
