#!/usr/bin/env ruby

keys = %w(read_ios   read_merges   read_sectors   read_ticks
	  write_ios  write_merges  write_sectors  write_ticks
	  in_flight  io_ticks      time_in_queue)

STDIN.each_line { |line|
	if line =~ /^time: /
		puts line
		next
	end

	data = line.split
	next if data.size != keys.size + 3

	dev_name = data[2]
	data[3..-1].each_with_index { |v, i|
		puts dev_name + '.' + keys[i] + ': ' + v
	}
}
