#!/usr/bin/env ruby

require 'json'

BW = 'bw'
IOPS = 'iops'

def parse
	fn = File.join ENV['RESULT_ROOT'], 'fio.output'
	res = JSON.load(File.read fn)
	unless res
		$stderr.puts 'Invalid/empty fio output'
		return
	end
	res_job = res['jobs'].first
	res_write = res_job['write']
	res_read = res_job['read']
	puts "write_bw_MBps: #{res_write[BW].to_f / 1024}"
	puts "write_iops: #{res_write[IOPS]}"
	puts "read_bw_MBps: #{res_read[BW].to_f / 1024}"
	puts "read_iops: #{res_read[IOPS]}"
end

parse
