#!/usr/bin/env ruby

stats = []

while (line = STDIN.gets)
  case line
  when /^(.*): (SUCCESS|FAIL)/
    stats_type = if $2 == 'SUCCESS'
                   'pass'
                 else
                   'fail'
                 end
    stats << $1.tr(' /', '_.') + ".#{stats_type}: 1"
  end
end

stats.uniq.each { |stat| puts stat }
