#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC']

require "#{LKP_SRC}/lib/statistics"
require "#{LKP_SRC}/lib/string_ext"

stats = []
testname = nil
mqueue_speed = {}
futex = {}

def futex_stat(line, futex, stats)
  case line
  when /^(futex.+): /
      futex['subtest'] = $1
  when /^\s+Arguments: (.+)/
      futex['argument'] = $1.tr(' ', '_')
  when /^Result\:\s+(PASS|FAIL)/
    if futex['argument'].nil? || (futex['argument'].include? 'none')
      stats << "futex.#{futex['subtest']}.#{$1.downcase}: 1"
    else
      stats << "futex.#{futex['subtest']}.#{futex['argument']}.#{$1.downcase}: 1"
    end
    futex['argument'] = nil
  end
end

while (line = STDIN.gets)
  line = line.remediate_invalid_byte_sequence(replace: '_') unless line.valid_encoding?

  case line
  when %r{make: Entering directory .*/(.*)'}
    testname = Regexp.last_match[1]
  when %r{make: Leaving directory .*/(.*)'}
    # rli9 FIXME: consider the input has messed text like Entering doesn't match with Leaving
    testname = nil
  when /^selftests: (.*) .*(PASS|FAIL)/
    stats << "#{testname}.#{Regexp.last_match[1]}.#{Regexp.last_match[2].downcase}: 1"
  when /Test #([1-9].*):/
    mqueue_test = Regexp.last_match[1]
  when /(Send|Recv) msg:/
    io = Regexp.last_match[1]
  when %r{(\d+) nsec/msg}
    mqueue_speed[mqueue_test + '.' + io] = Regexp.last_match[1].to_i
  when /: recipe for target.+failed$/
    next unless testname
    # do not count make fail in nr_test, which is for sub test number
    stats << "#{testname}.make_fail: 1"
  else
    futex_stat(line, futex, stats) if testname == 'futex'
  end
end

unless mqueue_speed.empty?
  stats << "mqueue.nsec_per_msg: #{mqueue_speed.values.average.to_i}"
end

stats.uniq.each { |stat| puts stat }
nr_test = stats.count { |k, _v| k !~ /\.make_fail/ }
puts "total_test: #{nr_test}" if nr_test.nonzero?
