#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/string_ext"

stats = {}

while (line = STDIN.gets)
  line = line.resolve_invalid_bytes
  case line
  when /\d*(not ok|ok).* - (.*)/
    result = $1.strip.tr(' ', '_')
    test = $2.strip.tr(' ', '_')
    stats[test] = result
  end
end

stats.each do |k, v|
  puts k + '.' + v + ': 1'
end
