#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/string_ext"
require "#{LKP_SRC}/lib/log"

stats = {}

while (line = STDIN.gets)
  line = line.resolve_invalid_bytes

  case line
  when /\d*(not ok|ok).* - (.*)/
    result = $1.strip.tr(' ', '_')
    test = $2.strip.tr(' ', '_')

    if stats[test]
      log_warn "test #{test} has already existed"
      exit 1
    end

    stats[test] = result
  end
end

result_mapping = {
  'ok' => 'pass',
  'not_ok' => 'fail'
}

stats.each do |k, v|
  v = result_mapping[v] || v

  puts k + '.' + v + ': 1'
end
