#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/string_ext"
require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

while (line = STDIN.gets)
  line = line.resolve_invalid_bytes

  case line
  when /\d*(not ok|ok).* - (.*)/
    stats.add $2, $1
  end
end

stats.dump('ok' => 'pass', 'not_ok' => 'fail')
