#!/usr/bin/awk -f

/PASS/ {
	printf("%s.pass: 1\n", $2)
}

/SKIP/ {
	printf("%s.skip: 1\n", $2)
}

/FAIL/ {
	printf("%s.fail: 1\n", $2)
}

/ignored_by_lkp:/ {
	printf("%s.ignored_by_lkp: 1\n", $2)
}

