#!/usr/bin/awk -f

BEGIN { nr_test = 0 }

/PASS/ {
	printf("%s.pass: 1\n", $2)
	nr_test += 1
}

/SKIP/ {
	printf("%s.skip: 1\n", $2)
	nr_test += 1
}

/FAIL/ {
	printf("%s.fail: 1\n", $2)
	nr_test += 1
}

/ignored_by_lkp:/ {
	printf("%s.ignored_by_lkp: 1\n", $2)
}

END { printf("total_test: %d\n", nr_test) }
