#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/log"
require "#{LKP_SRC}/lib/string_ext"

mtotal = nil
munit = nil
mused = []

STDIN.each_line do |line|
  line = line.resolve_invalid_bytes

  case line
  when /^time:/
    puts line
  else
    key, value, unit = line.split
    key = key.chomp(':')
    puts "#{key}: #{value}"
    value = value.to_i
    mtotal ||= value if key == 'MemTotal'
    if key == 'MemFree'
      mused << mtotal - value
      munit ||= unit
      puts "Memused: #{mused.last}"
    end
  end
end

puts "max_used_#{munit}: #{mused.max}"
