#!/usr/bin/ruby

total = {}
while line = STDIN.gets
	i, start_addr, end_addr, bytes, type = line.chomp.split ','
	total[type] ||= 0
	total[type] += bytes.to_i
end

total.each { |type, bytes|
	printf "%s: %d\n", type.tr(' ', '_'), bytes >> 10
}
