#!/usr/bin/env ruby
# example input:
# =========================================================================
# Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
# -------------------------------------------------------------------------
# Sets         1455.72          ---          ---      0.42200      1522.73
# Gets         5822.89       867.78      4955.10      0.40700      1088.00
# Waits           0.00          ---          ---      0.00000          ---
# Totals       7278.61       867.78      4955.10      0.41000      2610.72

$histo_sets_sum = Array.new(6,0)
$histo_sets_num = Array.new(6,0)
$histo_gets_sum = Array.new(6,0)
$histo_gets_num = Array.new(6,0)
$histo_waits_sum = Array.new(6,0)
$histo_waits_num = Array.new(6,0)
$histo_totals_sum = Array.new(6,0)
$histo_totals_num = Array.new(6,0)

def extract_memtier(line,histo_sum,histo_num)
  data = line.split
  (1..data.size - 1).each do |i|
    histo_sum[i] += data[i].to_f
    histo_num[i] += 1
  end
end

while (line = STDIN.gets)
  if line =~ /^Sets/
    extract_memtier(line,$histo_sets_sum,$histo_sets_num)
  elsif line =~ /^Gets/
    extract_memtier(line,$histo_gets_sum,$histo_gets_num)
  elsif line =~ /^Waits/
    extract_memtier(line,$histo_waits_sum,$histo_waits_num)
  elsif line =~ /^Totals/
    extract_memtier(line,$histo_totals_sum,$histo_totals_num)
  end
end

def gen_output_sum(type,histo_sum)
  puts "#{type}_ops_sum: #{histo_sum[1]}"
  puts "#{type}_hits_sum: #{histo_sum[2]}"
  puts "#{type}_misses_sum: #{histo_sum[3]}"
  puts "#{type}_latency_sum: #{histo_sum[4]}"
  puts "#{type}_kbs_sum: #{histo_sum[5]}"
end

def gen_output_avg(type,histo_sum, histo_num)
  avg_tmp=histo_sum[1]/histo_num[1]
  puts "#{type}_ops_avg: #{avg_tmp}"
  avg_tmp=histo_sum[2]/histo_num[2]
  puts "#{type}_hits_avg: #{avg_tmp}"
  avg_tmp=histo_sum[3]/histo_num[3]
  puts "#{type}_misses_avg: #{avg_tmp}"
  avg_tmp=histo_sum[4]/histo_num[4]
  puts "#{type}_latency_avg: #{avg_tmp}"
  avg_tmp=histo_sum[5]/histo_num[5]
  puts "#{type}_kbs_avg: #{avg_tmp}"
end

gen_output_sum("sets",$histo_sets_sum)
gen_output_sum("gets",$histo_gets_sum)
gen_output_sum("waits",$histo_waits_sum)
gen_output_sum("totals",$histo_totals_sum)
gen_output_avg("sets",$histo_sets_sum,$histo_sets_num)
gen_output_avg("gets",$histo_gets_sum,$histo_gets_num)
gen_output_avg("waits",$histo_waits_sum,$histo_waits_num)
gen_output_avg("totals",$histo_totals_sum,$histo_totals_num)
