#!/usr/bin/env ruby

RESULT_ROOT = ENV['RESULT_ROOT']

nr_test = 0
Dir["#{RESULT_ROOT}/**/*.csv"].each { |log|
	File.readlines(log).each do |line|
		if line =~ /(^LTP|^DDT)_[a-zA-Z0-9]+\;.+\;.*\;\d?\;\d?\;\d?\;$/
			nr_test = nr_test + 1
			result = line.split(";")
			if result[3] == "1"
				puts "#{result[0]}.#{result[1]}.pass: 1"
			elsif result[4] == "1"
				puts "#{result[0]}.#{result[1]}.fail: 1"
			end
		end
	end
}

puts "total_test: #{nr_test}"
