#!/usr/bin/env ruby

stats_name = 'fail: 1'

while (line = $stdin.gets)
  case line
  when /^package installed to \S+cgz$/
    stats_name = 'pass: 1'
    break
  when /^empty PACKAGE_LIST for .*$/
    stats_name = 'skip: 1'
    break
  end
end

puts stats_name
