#!/usr/bin/env ruby

while (line = STDIN.gets)
  case line.chomp!
  when /^\.\/(.*)\/(.*).pkt failed/
    puts $1 + '__' + $2 + '.fail' + ': 1'
  when /^\.\/(.*)\/(.*).pkt pass/
    puts $1 + '__' + $2 + '.pass' + ': 1'
  end
end
