#!/usr/bin/env ruby

results = Hash.new(0)

STDIN.each_line do |line|
  _, value, key = line.split
  next unless value =~ /^\d+$/
  results[key] += value.to_i
end

results.each do |key, value|
  puts "#{key}: #{value}"
end

results.each do |key, miss|
  next unless key =~ /(.*)-misses/
  stem = $1
  ['s', '-references', '-instructions'].each do |pfx|
    value = results[stem + pfx]
    next if value.zero?
    total = if pfx == 's'
              value + miss
            else
              value
            end
    puts "#{stem}-miss-rate%: #{miss * 100.0 / total}"
    break
  end
end

cycles = results['cpu-cycles']
instructions = results['instructions']

puts "ipc: #{instructions.to_f / cycles}" if cycles != 0 && instructions != 0

itlb_miss = results['iTLB-load-misses']

if itlb_miss != 0 && instructions != 0
  puts "instructions-per-iTLB-miss: #{instructions.to_f / itlb_miss}"
end
