#!/usr/bin/env ruby

stats = {}
while (line = STDIN.gets)
  case line
  when /^[ ]+\+ \S+\/(\S+)$/
    item = $1
  when /\.\.\.[ ]+([\S\s]+)$/
    stats[item] = $1.strip.to_s.tr(' ', '_').downcase
  end
end

stats.each do |k, v|
  puts k + '.' + v + ': 1'
end
