#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

while (line = STDIN.gets)
  case line
  when /([\d.]+:) (.*): FAILED!$/
    stats.add $2, 'fail'
  when /([\d.]+:) (.*): Ok$/
    stats.add $2, 'pass'
  when /([\d.]+:) (.*): [Skip$|Skip .*]/
    stats.add $2, 'skip'
  when /ignored_by_lkp: (.*)/
    stats.add $1, 'ignored_by_lkp'
  when /make perf failed/
    stats.add 'perf', 'make_fail'
  end
end

stats.dump
