#!/usr/bin/env ruby

test_id = -1
while line = STDIN.gets
	case line.chomp!
	when /pts\/(\S+)-[0-9.]+/
		test_name = $1
	when /Average: ([0-9.]+) (.*)/
		value = $1
		unit = $2
		test_id += 1
		unit = unit.downcase.gsub(' ', '_').gsub('/', '_')
		puts "#{test_name}.#{test_id}.#{unit}: #{value}"
	when /The following tests failed to properly run:/
		puts "has_failure: 1"
	when /idle-1.1.0.seconds/
	    puts "#{line.split()[1]}"
	end
end
