#!/usr/bin/env ruby
set_sum = 0
set_num = 0
set_avg = 0
get_sum = 0
get_num = 0
get_avg = 0
$stdin.each_line do |line|
  case line
  when /PING_INLINE: (\d+).(\d+) requests per second$/
    puts "PING_INLINE: #{$1}.#{$2}"
  when /PING_BULK: (\d+).(\d+) requests per second$/
    puts "PING_BULK: #{$1}.#{$2}"
  when /\WSET: (\d+\.\d+) requests per second$/
    set_sum += $1.to_f
    set_num += 1
  when /GET: (\d+\.\d+) requests per second$/
    get_sum += $1.to_f
    get_num += 1
  when /INCR: (\d+).(\d+) requests per second$/
    puts "INCR: #{$1}.#{$2}"
  when /LPUSH: (\d+).(\d+) requests per second$/
    puts "LPUSH: #{$1}.#{$2}"
  when /RPUSH: (\d+).(\d+) requests per second$/
    puts "RPUSH: #{$1}.#{$2}"
  when /LPOP: (\d+).(\d+) requests per second$/
    puts "LPOP: #{$1}.#{$2}"
  when /RPOP: (\d+).(\d+) requests per second$/
    puts "RPOP: #{$1}.#{$2}"
  when /SADD: (\d+).(\d+) requests per second$/
    puts "SADD: #{$1}.#{$2}"
  when /HSET: (\d+).(\d+) requests per second$/
    puts "HSET: #{$1}.#{$2}"
  when /SPOP: (\d+).(\d+) requests per second$/
    puts "SPOP: #{$1}.#{$2}"
  when /LPUSH .needed to benchmark LRANGE.: (\d+).(\d+) requests per second$/
    puts "LPUSH_LRANGE: #{$1}.#{$2}"
  when /LRANGE_100 .first 100 elements.: (\d+).(\d+) requests per second$/
    puts "LRANGE_100: #{$1}.#{$2}"
  when /LRANGE_300 .first 300 elements.: (\d+).(\d+) requests per second$/
    puts "LRANGE_300: #{$1}.#{$2}"
  when /LRANGE_500 .first 450 elements.: (\d+).(\d+) requests per second$/
    puts "LRANGE_500: #{$1}.#{$2}"
  when /LRANGE_600 .first 600 elements.: (\d+).(\d+) requests per second$/
    puts "LRANGE_600: #{$1}.#{$2}"
  when /MSET .10 keys.: (\d+).(\d+) requests per second$/
    puts "MSET: #{$1}.#{$2}"
  end
end
set_avg = set_sum/set_num
get_avg = get_sum/get_num
puts "SET_TOTAL: #{set_sum}"
puts "GET_TOTAL: #{get_sum}"
puts "SET_AVG: #{set_avg}"
puts "GET_AVG: #{get_avg}"
