#!/usr/bin/env ruby

while (line = STDIN.gets)
  case line.chomp!
  when /START TIME:\s(.*),\sEND TIME:\s(.*),\sTotal duration:\s(.*)\sseconds/
    puts "start_time.message: #{$1}"
    puts "end_time.message: #{$2}"
    puts "total_duration(s).message: #{$3}"
  end
end
