#!/usr/bin/ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($0)))
require "#{LKP_SRC}/lib/dmesg.rb"

error_ids = Hash.new

while line = gets
	id = common_error_id(line)
	next if id.size < 3
	error_ids[id] = line
end

error_ids.each { |id, line|
	puts '# ' + line
	puts id + ': 1'
	puts
}

if error_ids.size > 0
	puts 'has_stderr: 1'
end

if error_ids.size > 100
	STDERR.puts "WARN: noisy stderr, check #{ENV['RESULT_ROOT']}/stderr"
end
