#!/usr/bin/env ruby

stats = []
nr_test = 0

while (line = STDIN.gets)
  case line
  when /^(stutter).*(fail|pass)/
    stats_type = $2
    stats << $1 + ".#{stats_type}: 1"
    nr_test += 1
  end
end

stats.each { |stat| puts stat }
puts "total_test: #{nr_test}"
