#!/usr/bin/env ruby

while line = STDIN.gets
	next if line.index('Command being timed: ')
	key, val = line.split ': '
	key = key.gsub(/^\s+/, '').gsub(/ \([^)]+\)/, '').gsub(/\s+/, '_').downcase
	case key
	when 'elapsed_time'
		times = val.split ':'
		val = times.inject(0) {|tt, t| tt * 60 + t.to_f}
	when 'percent_of_cpu_this_job_got'
		val.chomp!("%\n")
		val = '0' if val == '?'
	end
	puts "#{key}: #{val}"
end
