#!/usr/bin/ruby

STDIN.each_line do |line|
	next if ! line.include? "TpmC"
	a = line.split
	next if a[1] == nil
	puts "TpmC: #{a[0]}"
end

def convert logfile
	outfile = File.basename(logfile, ".log") + ".plot"
	outf = File.new(outfile, "w")

	lines = File.open(logfile).read
	start = false
	lines.each_line do |line|
		if line.include? 'MEASURING START'
			start = true
		end
		next unless start
		break if line.include? "STOPPING THREADS"
		a = line.split('(')
		next if a[1] == nil
		outf.puts a[0]
	end
end

logfiles = Dir['./multi-bench*.log']

logfiles.each do |logfile|
	convert logfile
end
