#!/usr/bin/env ruby

while line = STDIN.gets
	case line.chomp!
	when /^System Benchmarks Index Score .* ([0-9\.]+)$/
		score = $1
	end
end

if score
	puts 'score: ' + score
else
	puts 'incomplete_result: 1'
	$stderr.puts "unixbench: missing score, check " + ENV['RESULT_ROOT']
end
