#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/string_ext"
require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

# skip invalid line
while (line = $stdin.gets)
  line = line.resolve_invalid_bytes

  break if line =~ /Required ioctls/
end

while (line = $stdin.gets)
  line = line.resolve_invalid_bytes

  case line
  when /test (.*): (FAIL|OK)*/
    stats.add $1, $2
  end
end

stats.dump('ok' => 'pass')
