#!/bin/bash

set -o pipefail

program_dir=$(dirname $0)
program=$1
stats_group=${2:-$1}
log=$RESULT_ROOT/$stats_group

check_incomplete_run()
{
	local file=$1

	[[ -s $file ]] && return
	[[ -f $LKP_SRC/tests/$program ]] || return

	echo -e "# missing $program $file\nis_incomplete_run: 1" >> $RESULT_ROOT/last_state
}

check_empty_output()
{
	[[ -s $log ]] && return
	[[ $program = 'tcrypt' ]] && return
	[[ $program = 'kernel-size' ]] && return
	[[ $program = 'perf-profile' ]] && return
	[[ $program = 'kmsg' ]] && return
	[[ $program = 'dmesg' && -s $RESULT_ROOT/.dmesg ]] && return

	rm -f $log $log.gz
	exit 0
}

warn_empty_stats()
{
	[[ -s $tmpfile ]] && return
	[[ $testbox =~ ^vm- ]] && return
	[[ $program = 'dmesg' ]] && return
	[[ -s $RESULT_ROOT/time ]] || return
	[[ -s $RESULT_ROOT/last_state ]] && return
	[[ $program = 'turbostat' ]] && grep -q -e 'No invariant TSC' $log && return
	grep -q "^$program\." $LKP_SRC/etc/failure && return

	echo "WARN: empty stats for $log" >&2
}

[ -f $log.gz ] && zcat $log.gz > $log

check_incomplete_run $log
check_empty_output

tmpfile=$(mktemp --tmpdir=/dev/shm lkp-stats.XXXXXXXX)
if [[ -f $log ]]; then
	$program_dir/$program $log < $log > $tmpfile || { echo "$program_dir/$program $log < $log  exit code $?, check $tmpfile" >&2; exit 1; }
else
	$program_dir/$program < /dev/null > $tmpfile || { echo "$program_dir/$program < /dev/null  exit code $?, check $tmpfile" >&2; exit 1; }
fi

grep -q "^$program\." $LKP_SRC/etc/failure ||
check_incomplete_run $tmpfile

warn_empty_stats

$LKP_SRC/sbin/dump-stat $stats_group	< $tmpfile || { echo "$LKP_SRC/sbin/dump-stat $program  exit code $?, check $tmpfile" >&2; exit 1; }
rm $tmpfile

[ -f $log.gz ] && rm $log

exit 0
