#!/usr/bin/env ruby

while line = STDIN.gets
	case line
	when /Failures: (.*)/
		fails = $1.split
		fails.each { |seq| puts "#{seq.tr('/', '.')}.fail: 1" }
		puts "nr_fail: #{fails.size}"
	when /^_check_generic_filesystem: filesystem on .+ is inconsistent \(see .+\/([a-z]+)\/([0-9]+)\.full\)/
		puts "#{$1}.#{$2}.inconsistent_fs: 1"
	when /^(generic|shared|ext4|xfs|btrfs|udf)\/(\d\d\d)\t (\d+)s/
		puts "#{$1}.#{$2}.seconds: #{$3}"
	end
end
