#!/bin/sh

# for packages with same dependencies, force the update instead of generating link
# due to schedule stage will auto detect symbolic link, so no need generate new link
check_shared_package()
{
	local bm_name="$1"

	[[ -L "$LKP_SRC/distro/depends/$bm_name" ]] || return

	local target
	target=$(readlink $LKP_SRC/distro/depends/$bm_name)
	target=$(basename $target)

	BM_NAME="$target"
}

show_deps_list()
{
	local blacklist="^pack-deps$
-dev$
-whitelist$"

	find $LKP_SRC/distro/depends/ -type f | sed 's:.*/::' | grep -v "$blacklist"
}

show_pack_list()
{
	local tmp_input="$(mktemp /tmp/lkp-tmpinput-XXXXXXXXX)"
	cat $(find $LKP_SRC/{monitors,setup,tests,daemon} -type f -or -type l|sed 's:.*/::') >$tmp_input
	find  $LKP_SRC/pack -type f | sed 's:.*/::' |
	grep -x -F -f <$tmp_input |
	grep -v -e '^0day-'
	rm $tmp_input &>/dev/null
}

