#!/bin/bash

. $LKP_SRC/lib/install.sh
. $LKP_SRC/distro/common

update()
{
	apt-get update
}

download()
{
	echo apt-get download $*
	apt-get download $*
}

hardlink_to_symlink()
{
	while read line
	do
		local hard_links=($line)
		for i in {1..9}
		do
			[[ ${hard_links[$i]} ]] || break
			echo \
			ln -sf ${hard_links[0]#.} ${hard_links[$i]}
			ln -sf ${hard_links[0]#.} ${hard_links[$i]}
		done
	done < <(for i in $(find . -type f -links +1); do find . -samefile $i | awk '{printf "%s ", $1}'; printf "\n"; done | sort | uniq)
}

install()
{
	for deb in *.deb; do
		dpkg-deb -x $deb .
	done

	hardlink_to_symlink
}

fixup_lkp-eywa()
{
	ln -sf /usr/bin/gnuplot-qt usr/bin/gnuplot
}

fixup_perf()
{
	local real_perf=(usr/bin/perf_*)
	[[ $real_perf ]] || return

	# replace the perf wrapper script
	ln -sf /$real_perf usr/bin/perf
}

pack()
{
	local date=$(date +"%Y-%m-%d")

	[[ $(type -t fixup_$BM_NAME) = 'function' ]] && fixup_$BM_NAME

	{
		find . -xdev ! -name "*.deb" |
		grep -v -f $LKP_SRC/rootfs/rootfs-strip-list

		[[ -f $LKP_SRC/distro/$DISTRO/$BM_NAME-whitelist ]] &&
		cat   $LKP_SRC/distro/$DISTRO/$BM_NAME-whitelist
	} |
	cpio --quiet -o -H newc --owner=root.root | gzip -n -9 > $pack_to/${BM_NAME}_$date.cgz
	ln -sf $pack_to/${BM_NAME}_$date.cgz   $pack_to/${BM_NAME}.cgz
	echo package installed to $pack_to/${BM_NAME}.cgz
}
